/**
 * Can Message中文配置文件
 * @since: 13-3-12
 */

Can.msg = {
	ERROR_TEXT: {
		ERR_ABNORMAL: '登录出现异常，请重新登录。',
		ERR_NORMAL_000: ':( 抱歉，我现在无法完成请求，请稍候再试。<br />如果问题依然存在，请与我们的客服联系：4006-280-333',
		ERR_LOGIN_000: '系统出错，请重新再试。',
		ERR_LOGIN_001: '邮箱/会员ID不正确。',
		ERR_LOGIN_004: '你的账号被禁止使用。',
		ERR_LOGIN_010: '你不能用广交会id号登录。',
		ERR_LOGIN_011: '你的账号还没有激活。',
		ERR_LOGIN_013: '你的会员套餐已过期，请购买新套餐。',
		ERR_LOGIN_014: '你还没有购买任何会员套餐',
		ERR_LOGIN_021: '邮箱未验证，你不能使用邮箱登录方式。',
		ERR_LOGIN_100: '用户名或密码错误。',
		ERR_UPLOAD_000: '上传失败，请稍后再试。',
		ERR_UPLOAD_100: '选择的文件超过上限。',
		ERR_UPLOAD_110: '文件大小超过上限。',
		ERR_UPLOAD_120: '不能上传空文件。',
		ERR_UPLOAD_130: '无效的文件类型。',
		ERR_UPLOAD_1100: '服务器没有接收到文件。',
		ERR_UPLOAD_1200: '不支持上传此类型文件。',
		ERR_UPLOAD_1300: '文件大小超过服务器限制。',
		ERR_UPLOAD_1600: '参数错误，请联系管理员。',
		ERR_EMAIL_000: '邮件填写不正确。',
		ERR_EMAIL_101: '邮件标题必须填写。',
		ERR_EMAIL_201: '请选择一个收信人。',
		ERR_EMAIL_301: '邮件内容必须填写。',
		ERR_PUSH_201: '请选择您想分享的产品！',
		ERR_TREE_000: '超出可选择范围。',
		ERR_TAG_001: '标注不能为空。'
	},
	VALIDATOR: {
		MIN_TIP: 'Not less than %s characters;',
		MAX_TIP: '不超过 %s 个字符'
	},
	UPLOADER: {
		DRAG_TIPS: '将文件拖到这, 可上传'
	},
	TEXT_BUTTON_VIEW: {
		REQUEST: '字段不能为空',
		LONG_LIMIT: '不能超过25个汉字',
		NUMBER: '* 只能是数字',
		PHONE_ZONENUM: '* 最多3位数字 ("+"号可选) (0-9)',
		PHONE_CODE: '* 只能是长度为1到4之间的数字 (0-9)',
		SIXFOUR: '* 最多64位数字 (0-9)',
		ONLY_PHONE: '* 手机号码必须为11位',
		EMAIL: '* 邮件地址无效',
		TOLONG_LIMIT: '* 最多128个字符',
		SEETING_TIME: '日期格式:HH:mm',
		PASSWORD_NOLIMIT: '* 只能是这之间的字符(A-Z, a-z, 0-9)',
		URL: ' * 无效的 URL',
		COMFIRM_PASSWORD: '* 请输入与上面相同的密码',
		LIMIT32: '* 最多32个字符',
		NOTWOFI: '* 最多256个字符',
		LIMIT16: '* 最多16位数字 (0-9)',
		CHECK_PASSWORD: '你输入的密码不正确',
		PASSWORD: '* 只能是长度为6到20之间的字符(A-Z, a-z, 0-9)',
		LIMIT50: '* Between 3 and 50 characters (A-Z, a-z, 0-9)',
		ONLY_ENGLISH: '* 请输入英文信息 ',
		CHECK_ACCOUNT: '这个账号已经存在',
		SKYPE_ERROR: '只能是6到32为数字或字母，且必须以字母开头'
	},
	APP_TITLE: {
		SUPPLIER: 'E-CantonFair - 供应商后台管理',
		BUYER: 'E-CantonFair - 采购商后台管理',
		EXPRESS: 'E-CantonFair - 广交会速递后台管理'
	},
	AJAX_ERROR: '<strong style="font-weight: bold;">AJAX请求出错！！</strong><br>地址：[@]<br />错误：[@@]',
	CHAR_LEFT: '个字符',
	PAGE_COUNT: '共[@]条',
	ALL: '全部',
	PAGE: {
		HOME: '首页',
		END: '末页'
	},
	BALANCE: 'C币余额',
	MEMBER_LEVEL: {
		'1': '体验会员',
		'2': '智航版会员',
		'3': '旗舰会员',
		'4': '至尊会员',
		'7': '钻石会员',
		'8': '铂金会员',
		'9': '广交会速递',
		'10': '预售会员',
		'11': '云服务会员',
		'12': 'E广通（终身制）',
		'13': 'E广通',
		'14': '中国优企',
		'15': '中国尊企',
		'16': '中国鼎企',
		'17': '预售e广通',
		'18': '无锡商务局项目会员',
		'L1': '会员信息',
		'L2': '会员类型',
		'L3': '到期',
		'L4': 'C币信息',
		'L5': '剩余',
		'L6': '总消费'
	},
	CATEGORY: '分类',
	NEED_COINS: '需要 <em>[@]</em> 个C币',
	COINS_NOT_ENOUGH: 'Notice: The C coins currently used to push is <em>[@]</em> Please call the Num:<em>4008517517</em>',
	MATCH_TIPS: '如何提高您的匹配效果？现在您可以 <a class="mdi-pref" href="javascript:;">设置好您对采购商的偏好</a> 或者 <a class="add-pro" href="javascript:;">发布更多的产品信息</a> 让我们对您的情况了解更多！',
	CREDIT_NOW: 'Credit Now!',
	ATTACH_FILE: '添加附件',
	NOT_MATCH_BUYER: '我们找不到相关的买家信息',
	NOT_MATCH_BUYER_SUGGEST: '我们建议您找一下采购需求',
	FAILED: '操作失败',
	DELETE_CONFIRM: '确定要删除相关项?',
	CHANGE_CONFIRM: '您确认放弃修改?',
	DOWNLOAD: '下载',
	PRICE: '价格',
	PRIVACY: {
		'PUBLIC': '公开',
		SECRET: '保密'
	},
	CAN_TITLE: {
		INQUIRY: '询盘',
		CHAT: '开始沟通',
		FAV: '收藏',
		EXP_NUM: '已参加广交会[@]次',
		BUSINESS_FOLLOW: '商务跟踪',
		CONTACT_CUSTOMER: '联系客户',
		MATCH: '与我的匹配度为[@]%%',
		CF_LEVEL: '广交会采购商信用等级为[@]',
		SINO_RATING: '买家 SinoRating 等级',
		NEW_PRODUCT: '新产品',
		BACK: '返回',
		MODIFY: '修改',
		COPY: '复制',
		OFFLINE: 'OFFLINE',
		ONLINE: 'Online',
		DELETE: '删除',
		VALID_EMAIL: '买家注册登记了邮箱',
		VALID_PHONE: '买家注册登记了电话',
		HOW_COUNT: '匹配度取决于您的商业规则设定以及产品范围。您可以通过修改商业规则，或者添加更多的产品区提高匹配的效果。'
	},
	DATETIME: {
		TODAY: '今天',
		BEFORE_MIN: '分钟前',
		BEFORE_SEC: '秒前'
	},
	ACCOUNT_MENU: {
		PROFILE: '个人资料',
		CHANGE_PWD: '修改密码',
		SET_BUSS: '设置商业规则',
		LOGOUT: '退出'
	},
	RULE_STEP: {
		BACK: '上一步',
		NEXT: '下一步',
		DONE: '完成'
	},
	IM: {
		YOURSELF: '自己',
		CHAT_NOW: '联系我',
		OFFLINE: '不在线'
	},
	//
	LOADING: '加载中...',
	PURCHASE: '采购品',
	MATCH: '匹配度',
	CREDIT: 'Credit',
	NOT_RELATED_PROD: '没有相关的产品',
	NOT_SEARCH_RESULT: '没有匹配的结果',
	NOT_SEARCH_SUGGEST: '检查您的搜索关键词拼写或者重新进行搜索',
	NOT_COLLECTION: '对不起，您还没有任何待处理商机：',
	NOT_COLLECTION_SUGGEST: '我们建议您马上搜索采购商或者产品',
	NOT_ACTIVITY: '对不起，没有找到符合您要求的采购商动态，我们建议您：',
	NOT_ACTIVITY_SUGGEST: '主动搜索符合您要求的采购商需求，并立即与采购商联系',
	PLEASE_LOGIN: '请登录',
	CANTON_FAIR_ID: '广交会ID或者邮箱地址',
	PASSWORD: '密码：',
	CODE: '验证码：',
	CODE_ERROR: '验证码错误！',
	CODE_REFRESH: '刷新',
	REMEMBER_ME: '记住我',
	FORGOT_PASSWORD: '忘记密码？',
	NOT_MEMBER: '还未注册',
	SIGN_UP: '注册 >>',
	FROM: '来自',
	REQUIRE_ACCOUNT: '请输入你的账号！',
	REQUIRE_PASSWORD: '请输入你的密码！',
	PRODUCT_LABEL: '产品',
	SUPPLIER_LABEL: '供应商',
	CHINA: '中国',
	BUTTON: {
		TOP_BAR_1: {
			HOME: '首页',
			SHOWROOM: '我的展台',
			MSG_CENTER: '消息中心',
			CUSTOMER_MANAGE: '客户管理',
			SETTING: '我的设置',
			SWITCH_EN: 'EN',
			SWITCH_CN: '中文',
			LANGUAGE: 'Language',
			LANGUAGE_EN: 'English',
			LANGUAGE_CN: '简体中文'
		},
		TOP_BAR_2: {
			//supplier
			MATCH_BUYER: '匹配采购商',
			ACTIVITY: '采购商动态',
			BUYING_LEAD: '采购需求',
			PRODUCT_FORM: '添加产品',
			MANAGE_PRODUCT: '产品管理',
			PRODUCT_COUNT: '产品统计',
			CAR_COUNT: '直通车统计',
			EXC_COUNT: '交换器统计',
			SHOWROOM: '我的展台',
			//buyer
			MY_ROOM: '私密橱窗',
			SEARCH: '搜索',
			COLLECTIONS: '待处理商机',
			MANAGE_BL: '管理采购需求',
			POST_BL: '发布采购需求'
		},
		SEARCH_BTN: '搜索',
		SEARCH_BL: '搜索采购需求',
		CONTACT_BTN: '联系我',
		VIEW_NOW: '现在浏览',
		VIEW_ACTIVITY: '查看动态',
		RETURN_LIST: '返回查看所有',
		MY_ACTIVITY: '我的动态',
		ALL_ACTIVITY: '所有动态',
		SIGN_IN: '登录',
		BR_PREV: '上一步',
		BR_NEXT: '下一步',
		BR_DONE: '完成',
		INQUIRY: '询盘',
		FAV: '收藏',
		ADD_NOW: '添加',
		ADD_Btn: '添加到',
		ADD_MORE_PRODUCT: '选择更多产品',
		RELATED_PRODUCT: '相关产品',
		//
		DATA_IDENT: {
			ITEM: '条',
			INQUIRY: '询盘信息',
			ACTIVITY: '买家动态',
			ACT_TIPS: '最近买家动态',
			PRODUCT: '橱窗产品',
			PRO_TIPS: '最新发布的产品',
			BUYING_LEAD: '采购需求',
			BL_TIPS: '最新未读采购需求',
			OPP: '待处理商机',
			INQ_REPLY: '询盘回复',
			BL_REPLY: '采购需求回复'
		},
		SELECT: '选择',
		RESELECT: '重新选择',
		DEL_PUSH_PRO: '删除产品',
		DEL_MSG: '删除消息',
		CONTACT_NOW: '联系我',
		PUSH_INFO: '推送',
		PUSH_INFO_TO_HIM: '向他推送',
		ADD_CONTACT: '添加到联系人',
		VIEW_DETAIL: '查看详情',
		SEARCH_NOW: '立即搜索',
		SEND: '发送',
		SURE: '确定',
		CANCEL: '取消',
		UPLOAD: '上传',
		SAVE: '保存',
		EDIT: '编辑',
		REPLY: '回复',
		DELETE: '删除',
		SEARCH: '搜索',
		RESTORE: '恢复',
		NEW_GROUP: '新分组',
		OK: '确定',
		YES: '是',
		NO: '否'
	},
	CREDIT_RATING: {
		AAA: '实力雄厚，抗风险能力很高，资信状况优秀',
		AA: '实力强，抗风险能力高，资信状况良好',
		A: '实力较强，抗风险能力较高，资信状况正常',
		BBB: '实力一般，抗风险能力一般，资信状况尚可',
		BB: '实力欠佳，抗风险能力欠佳，资信状况欠佳',
		B: '实力较弱，抗风险能力较低，资信状况较差',
		CCC: '实力弱，抗风险能力低，资信状况差',
		CC: '实力很弱，抗风险能力很低，资信状况很差',
		C: '企业濒临破产，基本无信用',
		NR: '因征信资料不全等特殊情况，不予评级',
		L1: '海外买家资信报告',
		L2: '在购买报告时，向我们提供买家的注册名称、注册地址',
		L3: '立即购买',
		L4: '购买流程',
		L5: '步骤',
		L6: '浏览报告样例',
		L7: '联系我们',
		L8: '用电子邮箱获得报告'
	},
	FORM: {
		SELECT_NORMAL: '-- Please Select One Item --',
		PRIMARY_KEYWORD: '主词',
		KEYWORD: '关键词'
	},
	SERVICES: {
		MENU_TITLE: '外贸服务',
		ZHONG_XB: '中国信保广电商信用保险',
		ZHONG_YTB: '中银广电商通宝',
		CARD_PAY: '国际信用卡收款'
	},
	MODULE: {
		BUYING_LEAD: {
			TITLE: '采购需求',
            TITLE_LINK: '在[<a style="color: #4db07a;" href="%s" target="_blank">搜索采购需求栏目</a>]里查看更多来自买家的采购需求。',
			ALL_BL: '推荐采购需求',
			MY_BL: '已报价的需求',
			UNVERIFY_BL: '审核未通过的商家需求',
			ALL_LABEL: '匹配的需求',
			CATE_LABEL: '产品分类',
			REGION_LABEL: '国家/地区',
			TIME_LABEL: '时间',
			TIME_ITEM: ['不限', '一个星期', '一个月', '三个月'],
			CATEGORY: '分类: ',
			QUANTITY: '数量要求: ',
			TIME_LEFT: '剩余时间: ',
			OFFLINE_TIME: '下线时间: ',
			POST_DATE: '发布时间: ',
			SECRET: '保密',
			NOT_MATCH_BL: '对不起，暂无符合您要求的采购需求，我们建议您：',
			NOT_MATCH_BL_SUGGEST: '主动搜索符合你要求的采购商，并立即向他们推送信息。',
			PUSH_SUGGEST: '通过浏览采购商动态发现他们第一手需求，并立即向他们推送信息',
			SUBJECT_PLACEHOLDER: 'Re: [@] Feedbacks from [@@]',
			REPLY_TIT_ERROR: '回复标题不能超过50字节',
			REPLY_CON_ERROR: '回复内容不能超过8000字节',
			REPLY_EPT_ERROR: '请输入具体回复内容！',
			ATTACHMENT: '附件',
			READ: '已读',
			UNREAD: "未读",
			SUCCESS: '发送成功',
			THIS_CANTON_FAIR: '114届广交会参展需求。由e-cnatonfair向申请参会买家获取.',
			SCENE_CANTON_FAIR: '114届广交会现场需求。由e-cnatonfair向现场买家获取。',
			MY_FAVORITE: '我喜欢的',
			LIEV_LEADEXPRESS: '广交会现场采购需求',
			LEADEXPRESS: '广交会参展需求',
			MATCH: '匹配采购需求',
			EMPTY: 'Empty',
			POST_TIME: '发布时间排序',
			TIP_MAX_SELECT: '最多选 %s 个',
			COMING_EXPIRED: '即将过期排序',
			SUBMIT: '提交',
			CLEAR_ALL: '清除',
			SELECTED: '已选 ：',
			COLLECTION_TIP: '把它放进你的收集，随时从“类型”选择阅读。',
			MORE_TIP: '查看更多',
			ALL_TYPE: '全部类型',
			RECOMMEND: 'VIP采购需求',
			AUTHORIZED: 'VIP委托采购需求',
			REWARD: '奖励',
			REWARD_TIPS: '当你回复这个需求，有机会获得奖励',
			VIEW_NOW: '查看详细',
			DIALOGUE_REFERENCE: '买家顾问与采购商对话参考（点击查看大图）',
			EXPORT: '出口市场：',
			ORDER_DATE: '预计下单时间',
			SCHEDULE: '采购商近期来华安排',
			COMP_INTRO: '公司简介：',
			YEAR_ESTABLISH: '成立年份：',
			COMP_WEBSITE: '公司网址：',
			OTHER_CONTACT: '其他联系方式',
			SUCCESS_REPLY: '您已成功回复采购需求！',
			TIPS: '建议您在广电商平台回复的同时，通过线下的邮箱或即时沟通工具与买家联系！',
			VIP_BUYING: 'VIP委托采购需求',
			PRODUCT: '产品图片（点击查看大图）：',
			FAX: '传真：',
			COMPANY: '公司名称：',
			MORE_INFO: '更多贸易信息和要求',
			SKYPE: 'Skype',
			FACEBOOK: 'Facebook',
			REPLY_SUCC_CON: '<div class="reply-succ"><h4><i class="icons current"></i>&nbsp;&nbsp;您已成功回复采购需求！</h4><p>建议您在广电商平台回复的同时，通过线下的邮箱或即时沟通工具与买家联系！</p></div>'
		},
		CF_BUYER_INFO: {
			CONTACT: '联系人',
			COUNTRY: '国家',
			COMPANY: '公司名称',
			EMAIL: 'Email',
			TELEPHONE: '联系电话',
			FAX: '传真',
			ADDRESS: '地址',
			CONTACT_TIT: '联系'
		},
		BUYER_ACTIVITY: {
			TITLE: '采购商动态',
			CATEGORY: '分类',
			COUNTRY: '国家',
			ACTION_TYPE: '行为类型',
			LATEST: '最近',
			LOAD_MORE: '加载更多'
		},
		BUSINESS_SET: {
			TITLE: '提示：为了采购商更好找到您和您更精准地找到所需要的采购商，请认真设置您的商业规则。',
			STEP1_TITLE: '你经营的行业<em class="tips">(最多可以选择2个经营的行业)</em>',
			STEP2_TITLE: '你的主营产品分类是<em class="tips">(最多可以选择40个主营产品分类)</em>',
			STEP3_TITLE: '您的主要出口市场有哪些？',
			STEP3_TITLE_1: '贸易区<em>（您最多可以选择12个）</em>',
			STEP3_TITLE_2: '贸易国家及地区<em>（您最多可以选择20个）</em>',
			ERROR_1: '对不起，最多只能选择[@]项。',
			ERROR_2: '请至少选择一项'
		},
		PRODUCT_FORM: {
			TITLE: '添加新产品',
			TIP: '<span class="bg-ico required"></span> 号为必填项，为满足采购商阅读需要，请用英文填写产品信息。',
			TITLE_1: '基本信息',
			EXR_TIPS_1: '为了帮助买家清楚地理解你的产品，这些信息也会影响你的产品在搜索结果中的排名。',
			PRODUCT_NAME: '产品名称：',
			PRODUCT_MODEL: '型号：',
			PRODUCT_VIDEO_URL: '视屏链接: ',
			//PLACEHOLDER: '请输入产品名称',
			CATEGORY: '分类：',
			PRIMARY_KEYWORD:'主词：',
			KEYWORD: '关键词：',
			PHOTO: '产品图片：',
			ATTACHMENT: '附件: ',
			UPLOAD: '上传',
			UPLOAD_TIPS: '支持的格式：<em>Jpeg, Jpg, Gif, or Png</em>；最大不超过3Mb 建议图片大小<em>600×600</em>像素',
			NEW_PRODUCT: '是否新产品：',
			GROUP: '分组: ',
			TITLE_2: '规格描述',
			EXR_TIPS_2: '全面和深入的描述有助于吸引更多的潜在买家。',
			INTRO: '简介： ',
			SPEC: '规格描述： ',
			TITLE_3: '贸易信息',
			EXR_TIPS_3: '完整的贸易信息帮助买家做出更好的决定',
			QUANTITY: '最小批量: ',
			SUPPLY: '月产量: ',
			PRICE: '离岸价格: ',
			PORT: '出货港口: ',
			PAYMENT: '付款方式: ',
			COUNT_LETTER: '当前还剩下字符[@]字符，总字符长度为250字符',
			REQUIRE: '表单不能为空.',
			VIDEO_URL_TIPS: '视屏链接提示:<br/>*请上传产品视频,要求视频尽量使用英文字幕或英文配音<br/>*视频应以展示该产品的样式、制造工艺、产品认证或资质等产品介绍为主<br/>*请勿使用非本平台其他同行的视频链接，建议使用youtube，metacafe，video google等国外买家常用视频网站平台',
			VIDEO_URL_FILTER_TIPS: '请勿使用非本平台其他同行的视频链接，建议使用youtube,metacafe,video google等国外买家常用视频网站平台',
			INVALID_URL_TIPS: '不正确的视屏链接',
			NON_CHINESE: '请输入英文信息',
			LETTER_TIPS: '10-150字符',
			selectProduct: '请选择产品分类',
			PRIVACY_STE: '私密设置',
			OPEN: '开放',
			PRIVACY: '私密',
			PRIVACY_STE_TIPS: '开放状态：该产品能被未登录访客查询；\n私密状态：该产品只能被买家查询。',
			TIPS: "在提交产品前，请认真阅读本平台信息发布指引，并确保您所发布的信息不涉及到虚假和侵权行为，如发布的信息有违此指引内容，本平台有权删除。",
			YES: '是',
			NO: '不是',
			LC: 'L/C',
			TT: 'T/T',
			DP: 'D/P',
			MG: 'Money Gram',
			CC: 'Credit Card',
			PP: 'Paypal',
			WU: 'Western Union',
			CA: 'Cash',
			ES: 'Escrow',
			OT: '其它',
			SAVE: '保存',
			GROUP_PLACE: '选择分组',
			GROUP_TEXT: '新分组',
			CREATE_GROUP_NAME: '输入新的分组名称',
			ERROR_TIPS: '分组名重复，请尝试另一个',
			ADD_TO: '添加到',
			ADD: '添加',
			MONEY_UNIT: '货币单位',
			UNIT: '单位',
			PER: '每',
			PN_1: '一个有效的产品名称应该包括<br>* 核心属性或参数<br>* 型号<br>* 相关认证能力',
			RRIMARY_KEYWORD: '主词提示 <br/>* 请使用最能体现此产品核心的单词或词组<br/>* 可结合分类leafcat及同义词，填写主词内容<br/>* 输入内容不能超过30个字符',
			KEYWORD_1: '关键提示：<br>* 产品名称的同义词<br>* 常用的产品名称<br>* 产品的相关联词',
			DETAIL_1: '* 详尽描述。以下的要素可供参考：<br>&nbsp;&nbsp;--特征<br>&nbsp;&nbsp;--功能<br>&nbsp;&nbsp;--质量标准<br>&nbsp;&nbsp;--认证<br>&nbsp;&nbsp;--服务等<br>* 利用多维度的相片进行描述，包括包装图，设计图等<br>* 分点描述，详略得当',
			/*
			 Outline your strengths & competence to attract more of your target buyers' traffic.	用一句话来展示产品卖点和竞争优势，呈现在搜索结果列表中，有效吸引买家点击发送询盘。
			 Format:Jpg/Jpeg, Gif, Png; Each Maximum Size:3MB; Suggest Picture Size:600*600 pixels	支持的格式：Jpeg, Jpg, Gif, or Png；最大不超过3Mb，建议图片大小600×600 像素
			 */
			LOAD_PORT_BAN_TXT: '请输入装货港',
			TEXT_MIN_LEN: '请至少输入 {0} 字符',
			TEXT_MAX_LEN: '最多输入 {0} 字符',
			FOB_PRICE_TIPS: '离岸价格不合理',
			DIGITS: '请只输入数字',
			MAX: '请输入一个少于或等于9999999999的数值',
			NUMBER: '请输入有效数字',
			SELECT_FILE: '选择文件',
			SENSITIVE_WORD: '您输入的内容带有“@”，有可能涉及侵权，请确认是否继续提交？',
			SAME_NAME: '您重复使用同一产品名称和型号，请按照新建产品特性进行描述和优化。'
		},
		PRODUCT_DETAIL: {
			MATCH: '匹配度:',
			MAIN_PRODUCT: '产品范围:',
			CONTACTER: '联系人:',
			CERT: 'Certification:',
			PRICE: 'FOB价格:',
			PORT: '离岸港:',
			QUANTITY: '最小订单量:',
			ABILITY: '供货能力:',
			PAYMENT: '付款方式:',
			TAGS: '标签:',
			INTRO: '简介:',
            VIDEO_DISPLAY:'视频展示',
			SPEC: '详细描述',
			CONTACT_NOW: '立即联系',
			SUBJECT: ' 主题:',
			CONTENT: '消息:',
			INQUIRY: '询盘',
			FAVORITES: '感兴趣',
			ADD_TAG: '给这个产品添加标签',
			TIP: '你可以从你的收藏中调用。',
			COLLECT: '已添加!',
			SUBJECT_PLACEHOLDER: 'Re: Write a Email',
			NO_PRODUCT_TIPS: '对不起! 系统找不到你需要的产品，<span>该产品已经下线。</span>',
			NO_PRODUCT_TIPS_2: '<span>10 seconds to post what you want!</span>Thousands of buyers are trying to use it,and you?',
			OR: 'or',
			POST_BL_BTN: 'Post Lead Express',
            VIDEO_DISPLAY:'视频展示'
		},
		MY_ROOM: {
			TITLE: 'My Room',
			NOT_DATA_TIPS: '对不起，您暂时没有任何推送消息',
			NOT_DATA_SUGGEST: '我们建议您马上搜索供应商或者产品。',
			LOAD_MORE: '查看更多推送信息'
		},
		OPPORTUNITY: {
			EGG_TIP1: 'Sourcing Egg, your onsite information collector.',
			EGG_TIP2: 'Everytime you scanned the sourcing egg, the corresponding information will be saved here, so that you <br/> could check anytime, anywhere.',
			MATCH: 'Match:',
			SCAN_TIME: 'Scan time: ',
			TITLE: 'Opportunity',
			CATEGORY: 'Category',
			TAG: 'Tag',
			PRODUCTS: 'Products',
			CONTACT: 'Contact: ',
			SOURCE: 'Source',
			HOME_TIP: 'Good job! Finally you get here.<br/> What you have scanned on the venue will be saved <a href="">here.</a>',
			COLLECTIONS: 'Collections',
			SOURCING_EGG: 'Sourcing Egg'
		},
		SEARCH: {
			TITLE: '搜索商机',
			CANTON_FAIR_ID: '广交会ID：',
			CONTACTER: '联系人：',
			MAIN_PRODUCT: '主营产品：',
			MIN_ORDER: '最小订单量：',
			FOB: 'FOB Price:',
			PAYMENT: 'Payment Tems:',
			SUPPLY: 'Supply Ability:',
			MGNT: 'Mgnt Certification:',
			SEARCH_NORMAL: '供应商',
			SEARCH_SELECT: ['产品', '供应商'],
			SEARCH_ADV: '高级搜索',
			SEARCH_BACK: '返回',
			TYPE: '类型:',
			KEYWORD: '关键字:',
			INDUSTRY_TYPE: '行业/分类:',
			SEL_INDUSTRY: '请选择产品分类',
			SEL_COMPANY: '请选择公司类别',
			NOT_RELATED: '暂时没有产品',
			CFER: '广交会参展商',
			TIP: '当前搜索根据您的预先设置显示结果，如分类，目标市场等，[@]。',
			VIEW_MY_PREFERENCE: '查看我的设置',
			SEARCH_NOT_RESULT_TIPS: 'Want to get the matched suppliers and detailed quotations?',
			SEARCH_RESULT_PBL_ORANGE: '10秒就可以提交你想要的！',
			SEARCH_RESULT_PBL_BLACK: '数以千计的采购商正在使用它, 您呢？',
			SORTS_LESS: '收起',
			SORTS_MORE: '展开',
			SORT_BY: '排序：',
			PREV: '前一页',
			NEXT: '后一页',
			HOME: '首页',
			TOTALCOUNT_PRODUCT_INFO: "个产品",
			TOTALCOUNT_SUPPLY_INFO: "个供应商",
			EXHIBITOR: '广交会参展商',
			NON_EXHIBITOR: '非广交会参展商',
			NARROW_DOWN_INFO: '按采购偏好缩小搜索范围',
			LEAD_EXPRESS: '发布采购需求',
			LEAD_EXPRESS_TIPS: '花1分钟快速发布采购需求，你会发现它的神奇之处！',
			LEAD_EXPRESS_ACTION: '知道了',
			COMPANY_TYPE: '公司类型',
			MANUFACTURER: '制造公司',
			TRADING_COMPANY: '商贸公司',
			MANUFACTURE_TRADE_COMPANY: '制造与商贸公司',
			OTHER: '其他公司',
			ADD_MORE_REGION: '添加更多地区',
			REGION: '地区',
			EAST_CHINA: '华东地区',
			NORTH_CHINA: '华北地区',
			WEST_CHINA: '西部地区',
			CENTRAL_CHINA: '华中地区',
			SOUTH_CHINA: '华南地区',
			BOOTH_NO: '115届展位号',
			PHASE: '期',
			EXHIBITOR_NO: '广交会',
			KEYWORD_ERROR_INFO: '请输入关键字进行搜索',
			INQUIRY_EXHIBITOR: '查看展台'
		},
		MY_CONTACTS: {
			TITLE: '我的联系人',
			ALL_GROUP: '所有分组',
			PRIVACY: '信息设置',
			CONTACTER: '联系人',
			MATCH: '匹配度',
			SETTING: '信息设置',
			LATEST_CONTACT: '最后联系',
			OPERATE: '操作',
			ADD_TO: '移动到',
			GROUP_TEXT: '创建分组',
			DEL_TIPS: '删除成功!',
			DEL_FAIL: '删除失败!',
			GUEST_TYPE: '客户类型',
			RELATIONSHIP_LEVEL: '关系等级',
			SYMBIOSIS: '合作关系',
			VAL_ASSESSMENT: '价值评估',
			CREDIT_RATING: '信用评估',
			PARTNER: '合作关系',
			VAL_ASSESSMENT_BUYER: '价值评估',
			CREDIT_RATING_BUYER: '信用评级',
			EXH_DETAIL: '参展详情@',
			CLIENT_TYPE: {
				POTENTIAL: '潜在客户',
				NORMAL: '普通客户',
				AGENCY: '代理商',
				PERSONAL_CLIENT: '个人客户',
				INVALID: '无效'
			},
			RELATIONSHIP: {
				CLOSE: '紧密',
				BETTER: '好',
				NORMAL: '一般',
				BAD: '坏'
			},
			COOPERATION: {
				FOLLOWING: '售前跟踪',
				CONTRACT: '合同阶段',
				COOPERATION_STAGE: '合作阶段',
				EOF_CONTRACT: '合同期满'
			},
			ASSESSMENT: {
				VERY_HIGH: "非常高",
				HIGH: "高",
				MIDDLE: '一般',
				LOW: '低',
				VERY_LOW: '非常低'
			},
			CREDIT: {
				VERY_HIGH: "非常高",
				HIGH: "高",
				MIDDLE: '一般',
				LOW: '低',
				VERY_LOW: '非常低'
			},
			PRIVATE_OPEN: '私密信息已开放',
			TRACE: '商务跟踪',
			NOT_NULL: '不能为空',
			LONG: '字数太多',
			MODIFY: '修改',
			MODIFY_FAIL: '修改失败',
			DELETE: '删除成功!',
			DELETE_FAIL: '删除失败！',
			SELECT_SOMEONE: '请选择一个以上的联系人',
			SET_GROUP_TIPS: '已经为该联系人添加了标签。',
			VIEW_ALL: '返回查看所有',
			NOT_CONTACT: '对不起，没有匹配结果：',
			TRY_AGAIN: '请检查您的搜索关键词拼写或者重新进行搜索。'
		},
		PRODUCT_MANAGE: {
			ON_LINE: '上线',
			OFF_LINE: '下线',
			STATUS: '状态:',
			ALL: '全部',
			PASS: '通过',
			MASK_AS: '标记为',
			PENDING: '待审',
			REJECTED: '拒绝',
			SHOWCASE: '橱窗产品',
			TITLE: '产品管理',
			ADD_PRODUCT: '添加产品',
			STATE: '产品统计',
			MARK_NEW: '新产品',
			MARK_FAIL: '设置为新产品失败',
			NAME: '产品名称',
			GROUP: '分组',
			NOT_GROUP: '未分组',
			LAST_MODIFY: '最后修改',
			ACTION: '操作',
			CREATE_GROUP: '新分组',
			EDIT_GROUP: '修改',
			EDIT_GROUP_FAIL: '操作失败',
			DEL_GROUP: '删除',
			MIN_ORDER: '最小批量:',
			FOB_PRICE: '离岸价格:',
			PAYMENT: '付款方式:',
			SUPPLY: '月供给能力:',
			DEL_TIPS: '删除成功！',
			DELETE_FAIL: '删除失败',
			MARK_SUCCESS: '标记成功！',
			ADD_GROUP_PROMPT: '产品已经添加到 [@] ',
			CHECKED_TIPS: '请选择产品',
			ALL_GROUP: '所有分组',
			MULTI_SET_GROUP: '产品已经添加到 [@] ',
			SET_GROUP_FAIL: '设置分组失败',
			NOT_NULL: '字段不能为空',
			LONG: '字数太多',
			DATA_EMPTY: '对不起，你还没有添加任何产品信息',
			PRODUCT_FORM: '立即发布产品',
			SEARCH_EMPTY: '对不起，没有匹配的结果：',
			SEARCH_TIPS: '请检查您的搜索关键词拼写或者从新进行搜索。',
			SEE_ALL: '返回查看所有',
			DELETE_ERROR: '请清空该组产品后再删除分组。',
			NOT_SHOWCASE: '你暂不能设置橱窗产品，<br>请升级套餐',
			NOT_TIP: '不再提示',
			SHOWCASE_TIP: '你一共可以设置 %s 个橱窗产品',
			SHOWCASE_SELECTED: '你还可以选择 %s 个橱窗产品',
			REASON: '原因: ',
			SHOWCASE_MAX_TIP: '您的橱窗产品数为 %s 个，<br>设置已超过上限！'
		},
		MSG_CENTER: {
			TITLE: '消息中心',
			SELECT_LABEL: ['全部', '已读', '未读'],
			SEARCH_LABEL: ['全部', '询盘', '邮件', '系统消息'],
			SOURCE_LABEL: ['全部', '收件箱', '发件箱'],
			DELETE: '删除',
			ADD_TO_CONTACTER: '添加到联系人',
			EXPORT: '导出',
			ALL_TYPE: '全部',
			SENDER: '发件人',
			RECIPIENT: '收件人',
			SUBJECT: '主题',
			TYPE: '类型',
			NO_MSG: '对不起，暂时没有任何消息记录',
			NO_MATCH: '对不起，没有匹配的结果',
			TIP: '请检查您的搜索关键词拼写或者重新进行搜索',
			MY_CONTACT0R_TIP1: "加为联系人",
			MY_CONTACT0R_TIP2: "已添加为联系人",
			READ: "已读消息",
			NOT_READ: "未读消息",
            ATTENTION:'注意',
			TYPE1: "询盘消息",
			TYPE2: "邮件消息",
			TYPE3: "系统消息",
			NAME_P: "查看名片",
			COMPOSE: "撰写邮件",
			INBOX: "收件箱",
			OUTBOX: "发件箱",
			SPAM: "垃圾箱",
			RESTORE: "恢复",
			DELETE_FOREVER: "彻底删除",
			RESTORE_SUCCESS: "恢复成功！",
			RESTORE_FAIL: 'Restore Fail1',
			SELECTED: "请选择列表！",
			MOVE_TRASH: "成功移动邮件到垃圾箱!",
			DEL_SUCCESS: "删除成功！",
			ADD_CONTACT_SUCCESS: "添加联系人成功！",
			SEND: "消息已被发送",
			DELETE_FAIL: '删除失败',
			VIEW_MORE: '查看消费详情',
			SYS_SENDER: 'E-cantonFair.com',
            UNVERIFY: 'Unverify'
		},
		SHOWROOM_SET: {
            CONFIRM_LEAVE : '本页面要求您确认您要离开 - 您输入的数据可能不会被保存。',
            CONFIRM_LEAVE_YES: '确认离开',
            CONFIRM_LEAVE_NO: '留在页面',
            OTHER_URL_TIP: '输入竞品网站网址，请重新输入网站地址。',
			PREVIEW: '预览',
			TEMPLATE_SETTING: '展台设置',
			HTTP_SETTING: '域名设置',
			COMP_INFO: '公司信息',
			FACTORY_INFO: '工厂信息',
			MARKET_INFO: '市场信息',
			PRODUCT_INFO: '产品信息',
			INFO_INTEGRITY: '信息完整度',
			SHOWROOM_INFO: '设置我的展台信息',
			COMP_INFO_TIPS_1: '<span class="bg-ico required"></span>号为必填项，修改已认证的信息，请联系客服: <em>4006-280-333</em>，协助修改。',
			COMP_INFO_TIPS_2: '<span class="bg-ico required"></span>号为必填项，修改已认证的信息，请联系客服: <em>4006-280-333</em>，协助修改。',
			COMP_INFO_TIPS_3: '请尽快完成展台信息填写并提交审核，确保您公司的E-booth顺利上线。',
			COMP_INFO_TIPS_4: '你的展台信息已提交审核，请耐心等待，如有问题请联系客服：4006-280-333',
			COMP_INFO_TIPS_5: '你的展台信息审核不通过，我们将有客服人员与你联系，指出需要修改的内容。',
			COMP_INFO_TIPS_6: '你的展台信息已审核通过。',
			AUDIT: '资料正在审核中',
			AUDIT_1: '保存并提交审核',
			MARKET_LABEL_1: '营业情况',
			MARKET_LABEL_2: '各地出口销售情况',
			MARKET_LABEL_3: '贸易条款',
			MARKET_LABEL_4: '主营产品',
			MARKET_LABEL_5: '热销产品',
			MARKET_LABEL_6: '新产品',
			MARKET_TIPS_1: '主要出口国或地区销售情况说明：',
			NOT_SALE_RECORD: "对不起，您当前还没有添加任何记录",
			NOT_PRODUCT_RECORD: "对不起，我们没有找到任何相关的产品信息",
			FISCAL_YEAR: '会计年度',
			YEAR_INCOME: '当年营业额：',
			EXPORT_RATE: '出口比例',
			YEAR_EXPORT_AMOUNT: '年出口销售额：',
			YEAR_SALE_AMOUNT: '年销售额',
			SALE_AREA: '贸易区',
			RATE_PERCENT: '所在比例',
			MAIN_CUSTOMER: '主要客户',
			NEW_PRODUCT_TOTAL: '当前上架的新产品共有',
			PRODUCT_NAME: '产品名称',
			PRODUCT_ACTION: '操作',
			MIN_ORDER: '最小订单量：',
			FOB: '离岸价格:',
			PAYMENT: '付款方式:',
			SUPPLY_ABILITY: '供应能力:',
			OFF_STORE: '取消新产品',
			MAIN_PRODUCT_CATE: '<span class="bg-ico required"></span>主营产品分类',
			SALE_PRODUCT_RATE: '<span class="bg-ico required"></span>销售额比重',
			SALE_PRODUCT_NAME: '<span class="bg-ico required"></span>产品名称',
			SALE_YEAR_AMOUNT: '<span class="bg-ico required"></span>年销售额',
			SALE_MIN_ORDER: '<span class="bg-ico required"></span>最小订单量',
			SALE_MAIN_CUSTOMER: '<span class="bg-ico required"></span>主要买家',
			MAIN_PRO_PD: '添加产品关键字',
			MAX_ITEM: '最多只可输入5条数据',
			ADD_NOW: '马上添加',
			SUCCESS: '成功',
			FAIL: '失败',
			DATA_LIMIT: '不允许输入8条以上的数据',
			REQUIRE: '必填数据不能留空！',
			VALID_NUMBER: '请输入符合要求的数字。',
			PERCENT_NUMBER: '请输入在0-100内的数字。',
			MAX_NUMBER_ERROR: "此处的数字不允许大于9,999,999,999",
			ADD_SALES_ERROR: '各贸易区的年销售额之和必须少于年出口销售额。',
			SAME_YEAR_ERROR: '不能重复添加同一个年份。',
			SALES_PROPORTION: '各类销售额占比之和必须小于100%',
			SELECT_BLANK_TXT: '--选择--',
			MAX_MAIN_PRODUCT: '主营产品不能多于6个。',
			MAX_PRODUCT_NAME: '主营产品名称不能大于20字符。 ',
			TEMPLATE: '展台装修',
			HTTPSETTING: '域名设置',
			HTTP_SERVICE: '修改已审核的信息，请联系客服: 4006-280-333，协助修改。',
			HTTP_NAME: '您展台的域名:',
			HTTP_HTTP: 'Http://',
			HTTP_COM: '.en.e-cantonfair.com',
			HTTP_NOTICES: 'Notice:',
			HTTP_NOTICETIPS: '• 自定义域名提交审核过后，为不可修改，如要修改请联系客服；<br/>• 域名自定义区域，最少三个英文字符以上，只可使用大小写英文、数字，不可使用特殊符号；<br/>• 不可使用www、地方拼音、敏感词汇等；',
			HTTP_PEND: '正在审核中',
			HTTP_NOMATCH: '域名不符合我们的要求，请重新',
			HTTP_SET: '填写提交',
			TEMPLATE_TIPS1: '带<span class="bg-ico required"></span>的模块为必须显示的，其他模块可以由用户自行决定是否显示。带<span class="icons arrow-6"></span>箭头的模块可以选择上下移动进行模板的排序',
			TEMPLATE_EDIT: '修改',
			TEMPLATE_BANNER: '自定义通栏大图（首页顶部通栏轮播）',
			TEMPLATE_NOTICE: '注：',
			TEMPLATE_BANNER_TIPS: '该模块主要是展示企业本身的宣传，分多图轮播方式和展台形式',
			TEMPLATE_BOOTH: '广交会参展商展位信息',
			TEMPLATE_BOOTH_TIPS: '如有过展位，该模块即会自动读取相关数据，如果没有展位该模块将会自动隐藏',
			TEMPLATE_YES: '显示',
			TEMPLATE_NO: '隐藏',
			TEMPLATE_COMPANY: '企业信息模块',
			TEMPLATE_COMPANY_TIPS: '该模块自动读取企业相关数据，目前你企业的信息完整度只有<span class="orange">%s</span>，请完善企业相关相关信息的完整度，更好地展示企业',
			TEMPLATE_CHANNEL: '橱窗产品展示',
			TEMPLATE_CHANNEL_TIPS: '您当前拥有的橱窗产品数量：<span class="orange">%s</span>个，最高可以设置<span class="orange">%s</span>个',
			TEMPLATE_CHANNEL_TIPS2: '建议你使用',
			TEMPLATE_CHANNEL_TIPS3: '您当前的套餐无法使用设置橱窗产品的功能，<a class="green" target="_blank" href="http://zh.e-cantonfair.com/custom-service">请升级您的套餐</a>',
			TEMPLATE_CHANNEL_TIPS4: '您当前拥有的橱窗产品数量：<span class="orange">%s</span>个，最高可以设置：<span class="orange">%s</span>个，建议设置数量不少于10个，现在就去<a class="green" href="#!/product-manage">设置橱窗产品</a>',
			TEMPLATE_NEWPRODUCT: '新产品展示',
			TEMPLATE_NEWPRODUCT_TIPS: '该模块自动读取最新%s个新品标签的产品信息。',
			TEMPLATE_NEWPRODUCT_TIPS2: '该模块自动读取最新12个新品标签的产品信息。您目前有<span class="orange">%s</span>个新产品',
			TEMPLATE_NEWPRODUCT_TIPS3: '该模块自动读取最新12个新品标签的产品信息。您目前只有<span class="orange">%s</span>个新产品，建议您先<a class="green"  href="#!/add-product">增加新产品数目</a>',
			TEMPLATE_MAINPRUDTCTS: '主营产品展示',
			TEMPLATE_MAINPRUDTCTS_TIPS: '该模块主要展示贵公司主要经营的产品类别，',
			TEMPLATE_SEND: '发布',
			TEMPLATE_BASE: '<span class="bg-ico required"></span>展台店招',
			TEMPLATE_RECOVER: '恢复',
			TEMPLATE_DIY: '自定义',
			TEMPLATE_DEFAULT: '使用平台默认店招',
			TEMPLATE_BASE_TIPS: '平台店招默认效果图',
			TEMPLATE_SET_BASETITLE: '设置我的企业店招',
			TEMPLATE_SET_REQUEST: '制作要求：',
			TEMPLATE_SET_REQUESTCONT: '1. 尺寸：宽度为1680px以上，高度为120px,大小不得大于2M的JPG或PNG格式的图片<br/>2. 背景图尽量简洁大气，突出企业文化或者主卖产品特色等。建议企业LOGO和企业名与背景图相融合',
			TEMPLATE_SET_STYLETIPS: '选择展现方式:',
			TEMPLATE_SET_STYLETIPS1: '完全自定义',
			TEMPLATE_SET_STYLETIPS2: '背景自定义',
			TEMPLATE_SET_STYLETIPS3: '通栏轮播',
			TEMPLATE_SET_STYLETIPS4: '展台轮播',
			TEMPLATE_SET_LEGEND: '图例',
			TEMPLATE_SET_SAMPLE: '下载样例',
			TEMPLATE_SET_UPLOAD: '上传我的店招',
			TEMPLATE_SET_UPBG: '上传我的背景图',
			TEMPLATE_SET_SELECTNAME: '选择企业名称的颜色:',
			TEMPLATE_SET_BANNER: '通栏大图设置',
			TEMPLATE_SET_BANNER_REQUIRE1: '需要您上传宽度为980px，高为300px，文件大小不超过1M的JPG或PNG格式的图片。',
			TEMPLATE_SET_BANNER_UPLOAD: '上传图片',
			TEMPLATE_SET_ADD_TIPS: '添加图片（<span class="orange"></span>/5）',
			TEMPLATE_SET_ADD_TIPS1: '添加图片（<span class="orange"></span>/9）',
			TEMPLATE_SAVE: '保存',
			TEMPLATE_SET_IPCNAME: '图片备注名',
			TEMPLATE_SET_PRODUCTS: '设置主营产品',
			TEMPLATE_SET_PRODUCTS_TIPS: '每个类别将会自动读取最新的前三个产品',
			TEMPLATE_SET_PRODUCTS_TIPS2: '您的分类',
			TEMPLATE_SET_PRODUCTS_TIPS3: '已选择(<span class="orange"></span>/7)',
			TEMPLATE_SET_SLLOWBG: '设置轮播背景：',
			TEMPLATE_SET_SLLOWTIPS: '需要您上传宽度为1680以上px，高为450px，文件大小不超过2M的JPG或PNG格式的图片。',
			TEMPLATE_SET_SLLOWPIC: '设置轮播图片：',
			TEMPLATE_SET_SLLOWPICIPS: '需要您上传250*250px，文件大小不超过500KB的JPG或PNG格式的图片。',
			ROW: '行',
			COL: '列',
			TEMPLATE_SET_HTTPSTIP: '请输入链接地址',
			TEMPLATE_SET_TIPS1: '该模块最少需要一张图片/继续添加图片',
			TEMPLATE_SET_TIPS2: '该模块最少需要三张图片/继续添加图片',
			TEMPLATE_SET_DEFALT: '使用平台默认',
			TEMPLATE_SET_UPLOADBG: '上传轮播背景',
			TEMPLATE_SET_SELECT_BOOTH: '选择参展届数:',
			TEMPLATE_SET_ADD_BOOTH: '添加展位号',
			TEMPLATE_SET_ADD_BOOTHPIC: '添加展位图片',
			TEMPLATE_SET_INNER_BOOTH: '请输入同个展馆的全部展位号',
			TEMPLATE_SET_ADD: '添加',
			TEMPLATE_SET_ADD_BOOTHNO: '新增展位号',
			TEMPLATE_SET_UPLOAD_PIC: '支持大小不超过2M的jpg、png图片上传',
			TEMPLATE_SET_BOOTH_NAME: '图片名称',
			TEMPLATE_SET_BOOTH_ADD_PIC: '新增展位图',
			TEMPLATE_SET_BOOTH: '设置展位信息',
			DOMAIN_TIPS: '该名称已经被占用，请重新填写',
			DOMAIN_TIPS1: '该名称格式不对,请重新填写',
			TEMPLATE_SET_SUCCESS: '保存成功',
			TEMPLATE_SET_TIPS3: '您的分类设置最少一个，不能多于7个。'
		},
		MATCH_BUYERS: {
			TITLE: '匹配采购商列表',
			CATEGORY: '分类',
			REGION: '地区',
			EXHIBITION: '参展次数',
			RECENTLY: '最近',
			COMP_TYPE: '公司类型',
			PURCHASE_LEVEL: '采购商级别',
			VIEW_HISTORY: '查看我的推送记录',
			SOURCING: '采购范围：',
			OTHER_FOCUS: '其他焦点：',
			SEE_MORE: '展开',
			SEE_LESS: '收起',
			FOCUS_MALE: '他',
			FOCUS_FEMALE: '她',
			FOCUS_DET: '[@]也关注<a href="javascript:;" role="buyer-sku-hit">[@@]</a>分类。',
			FOCUS_DETS: '[@]也关注<a href="javascript:;" role="buyer-sku-hit">[@@]</a>等其他<a href="javascript:;" role="buyer-sku-hit">[@@@]个产品分类</a>。',
			BUYER_ACT: '<em>最近动态：</em>我想要采购“<span>[@]</span>”',
			LOAD_MORE: '查看更多'
		},
		PRODUCT_STATISTICS: {
			TITLE: '产品访问量统计',
			PREVIEW_TIT: '时间段统计',
			AREA_TIT: '地区统计',
			NOT_DATA: '对不起，没有数据展示。',
			ITEM_WEEK: '一个星期',
			ITEM_MONTH: '一个月'
		},
		BUYER_LEAD_MANAGE: {
			TITLE: '管理采购需求',
			OPT_BTN: '发布采购需求',
			TAB_TIT_APPROVED: '审核通过',
			TAB_TIT_AUDITING: '审核中',
			TAB_TIT_UNAPPROVED: '审核不通过',
			TAB_TIT_EXPIRED: '过期的采购需求',
			TAB_TIT_OFFLINE: '下线的采购需求',
			SEARCH_KEYWORD: '关键词',
			DELETE: '删除',
			ONLINE: '上线',
			OFFLINE: '下线',
			PUBLISH_STATE: {
				0: '新增',
				1: '修改',
				2: '审核中',
				3: '审核通过',
				'-1': '审核不通过',
				9: '上线',
				10: '下线',
				'-3': '删除'
			},
			TABLE_HEAD_APPROVE: ['', '主题', '回复状态', '最新回复时间', '发布时间', '到期时间', '操作'],
			TABLE_HEAD_AUDITING: ['主题', '发布时间', '到期时间'],
			TABLE_HEAD_UNAPPROVED: ['', '主题', '不通过原因', '发布时间', '到期时间', '操作'],
			TABLE_HEAD_EXPIRED: ['主题', '发布状态', '回复状态', '最新回复时间', '发布时间', '到期时间'],
			TABLE_HEAD_OFFLINE: ['', '主题', '回复状态', '最新回复时间', '发布时间', '到期时间', '操作'],
			SAVE: '保存成功'
		},
		MY_SETTING: {
			TITLE: '我的设置',
			ACCOUNT_SETTING: '账户信息',
			PERSON_PROFILE: '个人信息',
			CHANGE_PWD: '修改密码',
			PREFERENCE_SET: '商业规则设置',
			PUSH_STATE: '推送统计',
			COMPANY_PROFILE: '公司信息',
			BUSINESS_SETTING: '商业规则设置',
			EXPRESS: '企业速递',
			ACCOUNT_MANAGEMENT: '账号管理',
			VERIFIED: '已认证',
			INFO_INTEGRITY: '信息完整度:',
			SAVE: '保存',
			BACK: '返回',
			ACCOUNT: '帐户 :',
			COMPANY_NAME: '公司名称 :',
			INTRO: '简介 :',
			DEPARTMENT: '部门 :',
			CATEGORY: '类别 :',
			CATEGORY_LABEL: '请选择产品类别',
			BUSINESS_TYPE: '公司类型 :',
			ESTABLISHED: '成立时间 :',
			FOUND: '成立时间 :',
			MAIN_KEYWORD: '主营产品关键字 :',
			REGION: '所属地区 :',
			COUNTRY_REGION: '国家/地区 :',
			ADDRESS: '中文地址 :',
			ADDRESS2: '地址 :',
			ADDRESS_EN: '英文地址 :',
			ZIP_CODE: '邮政编码 :',
			EMPLOYEE: '企业人数 :',
			REGISTER_CAPITAL: '注册资本 :',
			LEGAL_REPRESENTATIVE: '法人代表 :',
			BUSINESS_LICENSE: '工商证号 :',
			WEBSITE: '网站 :',
			UPLOAD: '上传',
			UPLOAD_TIPS1: '支持格式：<em>Jpeg, Jpg, or Png</em> ; 最大<em>200K</em>的<em>JPG图片格式</em>,建议图片尺寸为<em>160*160</em>',
			UPLOAD_TIPS2: '我保证我有权力使用和分配这幅照片，它没有违反使用条款',
			UPLOAD_TIPS3: '支持格式：<em>Jpeg, Jpg, or Png</em> ; 最大<em>200K</em>的<em>JPG图片格式</em>,建议图片尺寸为<em>160*80</em>',
			ACCOUNT1: '用户名 :',
			NAME: '姓名 :',
			FIRST_NAME: '姓名',
			LAST_NAME: '姓',
			GENDER: '性别 :',
			MALE: '男',
			FEMALE: '女',
			POST: '职位 :',
			AREA: '所属地区 :',
			TELEPHONE: '电话 :',
			FAX: '传真 :',
			MOBILE_PHONE: '手机 :',
			MOBILE_PHONE_CN: '中国手机号码 :',
			EMAIL: '电子邮件 :',
			ALTERNATE_EMAIL: '备用电子邮件 :',
			LANGUAGE: '语言 :',
			WORK_TIME: '工作时间 :',
			MEETING_TIME: '会议时间 :',
			SELECT: '请选择',
			PASSWORD: '密码 :',
			CURRENT_PWD: '当前密码 :',
			NEW_PWD: '新密码 :',
			CONFIRM_PWD: '确认密码 :',
			UPDATE_PWD: '修改密码',
			ACTIVATE_EMAIL: '激活邮箱登录',
			BASE_INFO: '基本信息',
			TRADING_INFO: '贸易信息',
			PRIVACY_SETTING: '隐私设置',
			AVATAR: '头像 :',
			CONTACT_INFO: '联系方式 :',
			TARGET_MARKET: '主要出口市场 :',
			BUSINESS_TIT_1: '您喜欢的采购商参加广交会的情况如何？',
			BUSINESS_TIT_2: '参加广交会次数 :',
			BUSINESS_TIT_3: '最近参展情况 :',
			BUSINESS_TIT_4: '您喜欢的采购商？',
			BUSINESS_TIT_5: '采购商类型 :',
			BUSINESS_TIT_6: '采购商性质 :',
			BUSINESS_TIT_7: '公司类型 :',
			BUSINESS_TIT_8: '公司性质 :',
			BUSINESS_TIT_9: '年采购量 :',
			PUSH_CONSUMPTION: '推送消费',
			TIMES: '推送次数',
			AVERAGE: '平均消费',
			PUSH_STATE_1: '推送效果统计',
			PUSH_STATE_2: '对不起，你还没有进行过信息推送',
			PUSH_STATE_3: '立即向采购商推送信息',
			TOTAL: '总数',
			PRODUCT: '产品',
			COMPANY: '公司',
			VIEWS: '查看次数',
			COLLECTED: '收藏次数',
			COLLECTED_RATE: '收藏率',
			PUSH_RECORD: '推送记录',
			TIME: '时间',
			CONSUMPTION: '消费',
			TO: '对象',
			PERFORMANCE: '效果',
			TIPS_TITLE_1: '输入正确的网址',
			TIPS_TITLE_2: '* 必填字段',
			TIPS_TITLE_3: '* 只能是长度为6到20之间的字符(A-Z, a-z, 0-9)',
			TIPS_TITLE_4: '* 请输入与上面相同的密码',
			TIPS_TITLE_5: '* 只能是数字',
			TIPS_TITLE_6: '* 至少11个数字',
			TIPS_TITLE_7: '提示：您可以使用电子邮件或者Canton Fair ID 登录WEB、APP和我们提供的任何终端。',
			TIPS_TITLE_8: '经常修改您的密码可以提高账号安全。',
			TIPS_TITLE_9: '公开头像，供应商将可以看到您的头像，令人感觉亲切和真实，建议你选择公开。一旦选择了“公开”选项，将默认您同意并授权广电商免费且永久使用权，您的头像信息将会被使用和展示，同时供应商将会看到相关信息。',
			TIPS_TITLE_10: '联络时自动向供应商公开信息（邮件地址、电话号码等联系方式）',
			TIPS_TITLE_11: '选择此项，每次你主动联系供应商时，比如：发送询盘、发送站内消息，都会向供应商公开您的邮件地址、电话号码等联系方式。',
			TITLE_TIPS: '<span class="bg-ico required"></span>号为必填项，修改已认证的信息，请联系客服: <em>4006-280-333</em>，协助修改。',
			SUCCESS_TIPS: '信息保存成功!',
			SEVRVER_INFO: '服务信息',
			BUSINESS_EXPRESS: '企业速递',
			EXP_PACKAGES: '套餐',
			EACH_BUYER: '每次推送买家数:',
			PUSH_TIME1: '推送次数:',
			EXP_STATE: '套餐状态:',
			EXP_STATETIME: '开始时间:',
			EXP_EXTIME: '过期时间:',
			EXP_SERTIME: '可服务次数:',
			EXP_HASTIME: '已服务次数:',
			EXP_RECORD: '企业速递记录',
			EXP_TIME: '执行时间',
			EXP_PUSHBUYER: '推送买家数',
			EXP_COUNTRY: '相关国家数',
			EXP_DETAIL: '详细',
			MARK_SELECT: '参加广交会次数和最近参展情况为必选!',
			IS_FAV: '已收藏',
			NO_FAV: '未收藏',
			SUCCESS: '保存成功',
			NO_PUSH: '对不起，你还没有进行过信息推送.',
			PUSH_NOW: '立即向采购商推送信息!',
			PWD_TIPS: '大写键盘已锁定',
			UPDATE_SUCCESS: '信息保存成功!',
			UPDATE_ERROR: '信息保存失败!',
			DELETE_SUCCESS: '子账号删除成功!',
			DELETE_ERROR: '子账号删除失败!',
			DELETE_ACCOUNT: '删除后该账号将无法使用。',
			ACCOUNT_NAME:'账号名称',
			ADD_SUB_ACCOUNT: '添加子账号',
			OPERATE:'操作',
			UPDATE:'修改',
			DELETE:'删除',
			BUYER_BUSINESS_TYPE: {
				'i0': '采购办事处',
				'i1': '制造商',
				'i2': '贸易公司 ',
				'i3': '批发商/经销商',
				'i4': '零售商',
				'i5': '经纪人/顾问委员会',
				'i6': '政府及机构',
				'i7': '其他'
			},
			BUSINESS_NATURE: {
				'i0': '制造商及大批发商',
				'i1': '中小批发商群体',
				'i2': '小零售商群体 ',
				'i3': '小贸易商群体',
				'i4': '其它群体'
			},
			ANNUAL_PURCHASE: {
				'i0': '1百万以下',
				'i1': '1百万到1千万',
				'i2': '1千万到5千万',
				'i3': '5千万到1亿',
				'i4': '1亿以上'
			},
			BUSINESS_SETTING_TIT: {
				'i0': '您感兴趣的产品范围',
				'i1': '您期望供应商的规模',
				'i2': '您期望供应商的性质'
			},
			BUSINESS_SETTING_LABEL: {
				'i0': {
					'title': '人员规模 :',
					'i0': '不限',
					'i1': '100以下',
					'i2': '5000以上'
				},
				'i1': {
					'title': '注册资金(百万) :',
					'i0': '不限',
					'i1': '1以下',
					'i2': '1-5',
					'i3': '5-20',
					'i4': '20-50',
					'i5': '50-100',
					'i6': '100-1000',
					'i7': '1000以上'
				},
				'i2': {
					'title': '年营业额(百万) :',
					'i0': '不限',
					'i1': '1以下',
					'i2': '1-10',
					'i3': '10-50',
					'i4': '50-100',
					'i5': '100以上'
				},
				'i3': {
					'title': '公司类型:',
					'i0': '生产企业',
					'i1': '外贸企业',
					'i2': '工贸企业',
					'i3': '其他'
				},
				'i4': {
					'title': '参展次数 :',
					'i0': '不限',
					'i1': '至少最近1界',
					'i2': '至少1界',
					'i3': '至少最近2界',
					'i4': '5界以上'
				}
			}
		},
		EXPINDEX: {
			MEMBER_LEVEL: {
				'L1': '会员类型',
				'L2': '到期',
				'L3': '会员升级'
			},
			PRO_TOTAIL: '产品数量',
			PUSH_TIME: '推送次数',
			PROCREDIT: '刷卡次数',
			HTO_BUYINGLEAD: '最热采购需求',
			WANT_GETBUYLEAD: '想获取这些采购需求',
			NO_EFFECT: '未生效'
		},
		STATISTICS: {
			TITLE_CAR: '直通车统计分析',
			CAR: '直通车统计',
			TITLE_EXCHANGER: '交换器统计分析',
			EXCHANGER: '交换器统计',
			DATE_LABEL: '统计日期',
			TO: '至',
			COUNTRY: '国家/地区',
			PUSH_BUYERS: '推送买家数量',
			SWIPE_BUYERS: '刷卡买家数量',
			READ: '阅读数量',
			READ_TOTAL: '阅读总数',
			PUSH_TOTAL: '推荐总量',
			SWIPE_TOTAL: '刷卡总量',
			PRE_PAGE: '上一页',
			NEXT_PAGE: '下一页',
			NAME: '名字',
			TIMES: '参展次数'
		},
		COINS_DETAIL: {
			TITLE: 'C币明细',
			COST: '总花费 :',
			BALANCE: '余额',
			TYPE: '类型',
			GIFT: '赠送',
			CONSUME: '消费',
			REWARD: '奖励',
			RECHARGE: '充值',
			TIME: '时间',
			DETAIL: '明细',
			PAYMENT: '付款',
			ALL: '全部',
			UNIT: '币',
			START_TIME: '开始时间',
			END_TIME: '结束时间',
			TIPS: '对不起，没有找到符合你要求的数据'
		}
	},
	BL_DETAIL: {
        NOT_SEARCH_RESULT: '没有与你匹配的采购需求',
        NOT_SEARCH_SUGGEST: '请上传您的产品匹配采购需求',
		SECRET: '保密',
		TIME_LEFT: '剩余时间 :',
		DATE_POST: '发布时间 :',
		UPDATE: '更新时间 :',
		CONTACT_NOW: '马上联系',
		ADD_CONTACTER: '添加为联系人',
		BASE_INFO: "基本信息",
		MORE_INFO: "更多信息",
		HISTORY: '联系历史',
		CATEGORY: '分类',
		PUR_AMOUNT: '采购金额',
		ANNUAL_AMOUNT: '年采购金额',
		DESCRIPTION: '描述',
		ATTACHMENTS: '附件',
		EXPIRATION_DATE: '过期时间',
		PURCHASE: '本次采购量',
		ANNUAL: '年采购量',
		MODE_OF_TRANSPORT: '运输方式',
		PREFERRED_PRICE: "首选价格",
		PORT_OF_ARRIVAL: "到达港口",
		SUPPLIER_REQUIREMENTS: "供应商要求",
		EXPECT_TO_RECEIVE: "期望接收",
		RECOMMEND: 'Recommended',
		UNVERIFY: 'Unverify',
		VERIFY: 'Verify',
		REPLY_HISTORY: '回复历史',
		MATCH: '匹配度：',
		SUBJECT: '标题:',
		CONTENT: '内容:',
		SEND: '提交',
		QUESTION: '我们如何处理你的回应? ',
		ANSWER1: '我们会把您的回复发送给买家。',
		ANSWER2: '为了让买家尽快看到您的回复，我们同时会把回复内容通过邮件方式发给他。',
        GUIDE_SING: '回复采购需求，请先 <a href="/login.html?ut=supplier" rel="nofollow">登录</a>.',
        GUIDE_SING2: '回复采购需求，请先 <a id="quote-login" href="javascript:;" rel="nofollow">登录</a>.',
        GUIDE_JOIN: '还不是会员? 马上 <a href="/joinfree/?tab=3" rel="nofollow">注册</a>.',
        CONTACT_DETAIL: '联系信息',
		MESSAGE: '详细信息',
		STATUS: "状态:",
		INQUIRY: '买家 <a href="javascript:void(0);">[@]</a> 已发送咨询。',
		SYSTEM_PUSH: '系统已推送给买家。',
		SUPPLIER_REPLY: '你回答的需求。',
		BUYER_READ: '买家已经阅读您的回复。',
		COMPANY: '公司：',
		CONTACT: '联系人：',
		EMAIL: '邮箱：',
		ADDRESS: '地址：',
		PUSH_EMAIL: '系统已经通过e-mail把你的回复发送给采购商。',
		BUSINESS_TYPE: '公司类型：',
		REGION: 'Region:',
		MAIN_PRODUCT: '主营产品：',
		TEL: '电话：',
		MOBILE_PHONE: '移动电话:',
		OTHER_CONTACT: '其他联系方式: ',
		FAX: '传真：',
		POST: '职位：',
		PAYMENT: '支付方式',
		EXPIRED_DATE: '过期日期 :',
		PURCHASE_AMOUNT: '本次采购金额',
		ANNUAL_PURCHASE_AMT: '年度采购金额',
		RECOMMEND_TIPS: '<span>e-CantonFair 买家顾问</span>已经和该采购商确认过采购需求，特意推荐给您。',
		VERIFY_TIPS: '该采购商已经通过e-cantonfair验证。',
		UNVERIFY_TIPS: '该采购商的联系信息尚未经过验证。',
		EXHIBITOR_TITLE: 'October Canton Fair Exhibitor',
		EXHIBITORS_BOOTH_TITLE: '114届展会展位信息',
		BOOTH_CLOSE_UP: '展位特写',
		NO_CONTACT_INFO: '采购商不愿意公开他的联系方式。',
		PHASE1: 'Phase 1:',
		PHASE2: 'Phase 2:',
		PHASE3: 'Phase 3:',
		PHASE4: 'Phase 4:',
		MORE: 'more',
		LESS: 'less',
		SPECIAL_PREFERENCES: 'Special Preferences',
		SUPPLIERS_REPLIE: '供应商的回复',
		REMINDER: '<span>注意：</span>以下显示的时间都是北京时间,GMT+8',
		EXHIBITOR_TIT: '我们10月广交会展览',
		BOOTH_NUM: '展位',
		TARGET_MARKET: '出口市场',
		CERTIFICATION: 'Mgnt 认证',
		SORRY_TXT: '对不起,没有回复目前。',
		ADVICE_TXT: '也许你可以试试下面的……',
		POST_BL: '发布采购需求',
		AD_TXT1: '10 seconds to post what you want!',
		AD_TXT2: 'Thousands of buyers are trying to use it,and you?',
		ADD_COMMENT: '回复',
		EXHIBIT_IN_OCTOBER: 'Exhibit in October',
		BUYER_INFO: '买家的联系信息',
		TIPS: '买家想通过广电商网站获得您的信息和联系方式。',
		CONTACT_BUYER: '联系买家',
		CONTACT_TIPS: '(为了认买家觉得你更可信，建议使用广电商网站的邮件通道与买家联系。)',
		INTER_MSG: '输入你的信息',
		YOUR_CONTENT: '你回复的内容:',
		MSG_DETAIL: '输入您的消息详细，可以如下:<br/> -产品详细描述<br/> -您的报价<br/> -您的生产能力',
		START_TIPS: '把它放进你的收集，<br/>随时从“类型”选择阅读。',
		SEND_SUCCESS: '发送成功！',
		PHONE: '电话 :',
		FROM: '发件人',
		TO: '收件人',
		L_DETAIL: '采购需求详细',
		NEED_COINS: '查看联系方式，需要花费 10 C币,',
		REWARD: '<span>提示:</span>成功回复这个采购需求，你将获得 ',
		TIPS_COINS2: 'C币奖励。',
		CONSUME: '<span>提示:</span>该需求已经获得足够的回复，回复这个采购需求，须消费 ',
		CONIS: '币',
		LIMIT: '联系方式申请已经超过上限，<br/>本次操作不需要任何C币。',
		C_COINS: '当你回复这个需求，有机会获得奖励',
        VIEW: '查看: ',
        RELY: '回复数: ',
        UNMATCH_TIPS: '<span></span>注: 此采购需求为非匹配采购需求，您无法查看买家联系方式，采购商获取您的报价后可通过平台跟您互动联系。',
        UNLOGIN_TIPS: '<span></span>查看买家联系信息，请先 <a href="javascript:;">登录</a>!',
        UNQUOTE_TIPS: '<span></span>注：回复报价，获取买家联系方式！',
        BUYER_TIPS: '<span></span>您是一个买家，不能查看买家的联系方式!',
        QUOTE_NOW: '立即报价',
        SELECT_PRO_TIPS: '选择从产品列表选择一个产品',
        RESELECT: '重选',
        YOUR_QUOTE: '你的报价: ',
        MOQ: '最少采购量: ',
        QUOTE_TILL: '报价有效期限: ',
        SELECT_PRO: '选择产品: ',
        QUOTE_DETAIL: '报价详细',
        YOUR_MESSAGE: '你的信息: ',
        QUOTE_FOR: '我的报价:',
        FORBID_TIPS1: '你是一名买家，不能报价采购需求.',
        FORBID_TIPS2: '你向匹配采购需求报价已达今天上限(100条)，请明天再回复.',
        TIP_TITLE_12: '提示',
        TIP_MSG: '虽然E-cantonfair.com旨在为您提供准确的发送人资料，我们无法完全保证每一个发送者的IP信息的准确性。 E-cantonfair.com既不负责也不承担任何有关上述信息。'
    },
	BUYER_ACTIVITY: {
		TIT: {
			BROWSE_PRO: '浏览了您的产品',
			BROWSE_INFO: '查看您的公司信息',
			EXCHANGE_CARD: '跟您交换名片',
			COLLECTED_PRO: '收藏了您的产品',
			COLLECTED_INFO: '收藏您的公司信息',
			SEND_INQ: '发送一条询盘信息给您',
			INTEREST: '对你的公司非常感兴趣',
			BROWSE_BE: '浏览了您的企业速递',
			BROWSE_PUSH: '查看了你的推送邮件',
			//all
			BROWSE_PRO_ALL: '浏览了产品',
			BROWSE_INFO_ALL: '查看了一个公司信息',
			EXCHANGE_CARD_ALL: '和一个供应商交换了名片',
			COLLECTED_PRO_ALL: '收藏了一个产品',
			COLLECTED_INFO_ALL: '收藏了一个公司信息',
			SEND_INQ_ALL: '发送了一个询盘',
			SEARCH: '想找一种产品',
			POST_BL: '发布了一条采购需求',
			ALL_ACTIVITIES: '所有动态',
			MY_STATUS: '我的动态'
		},
		DESC: {
			BROWSE_PRO: '来自 %(region)s 的 %(user)s 浏览了 "%(data)s" 分类下的产品',
			INDEX_BROWSE_PRO: '来自 %(region)s 的 %(user)s 浏览了产品 "%(data)s"',
			BROWSE_INFO: '来自 %(region)s 的 %(user)s 查看您的公司信息。',
			EXCHANGE_CARD: '来自 %(region)s %(data)s 行业的%(user)s收藏了您的名片，并添加到通讯录中。',
			COLLECTED_PRO: '来自 %(region)s 的 %(user)s 对 "%(data)s" 分类下的产品感兴趣',
			INDEX_COLLECTED_PRO: '来自 %(region)s 的 %(user)s 对产品 "%(data)s" 感兴趣',
			COLLECTED_INFO: '来自 %(region)s 的 %(user)s 收藏您的公司信息。',
			SEND_INQ: '来自 %(region)s 的 %(user)s 对产品 "%(data)s" 感兴趣',
			INTEREST: '来自 %(region)s 的 %(user)s 对您的公司非常感兴趣。',
			BROWSE_BE: '来自 %(region)s 的 %(user)s 浏览了您的企业速递',
			BROWSE_PUSH: '查看了你的推送邮件。',
			RBH: '最近访问历史',
			//all
			BUSINESS: '想要采购[%s]分类下的产品。',
			BROWSE_PRO_ALL: '来自 %(region)s 的 %(user)s 浏览了 "%(data)s" 分类下的产品',
			BROWSE_INFO_ALL: '来自 %(region)s 的 %(user)s 浏览了 %(data)s 分类下的一个公司信息。',
			EXCHANGE_CARD_ALL: '来自 %(region)s 的 %(user)s 分类下的一个供应商交换了名片。',
			COLLECTED_PRO_ALL: '来自 %(region)s 的 %(user)s 收藏了 %(data)s 分类下的一个产品。',
			COLLECTED_INFO_ALL: '来自 %(region)s 的 %(user)s 收藏了 %(data)s 分类下的一个供应商信息。',
			SEND_INQ_ALL: '来自 %(region)s 的 %(user)s 发送了一个询盘给 %(data)s 分类下的一个供应商。',
			SEARCH: '来自 %(region)s 的 %(user)s 搜索了关键词 “%(data)s”',
			POST_BL: '来自 %(region)s 的 %(user)s 发布了采购需求：“%(data)s”'
		},
		MORE_TIP: '查看更多',
		LIVE_TIP: '114届广交会采购商',
		PRIVATE_TIP: '<span class="red">注意:</span> 以下不可见的产品图片为开启了私密设置'
	},
	SELLER_INDEX: {
		SEARCH_BL: '搜索采购需求',
		ADD_PRO: '添加产品',
		INFO_INTEGRITY: '信息完整度：',
		IMPROVE: '完善信息',
		INTEREST: '你可能感兴趣的采购商',
		ALL_STATUS: '所有动态',
		MY_STATUS: '我的动态',
		ALSO_U_CAN: '或者你可以',
		KEYWORD: '关键词',
		NOTICE: '更新公告',
		NOTICE_CONTENT: '2月25日更新内容如下：',
		REWARD_TIP1: '平台网站展台&产品开放访问',
		TIP1_CONT1: '1.游客可搜索查看产品及供应商列表，并且无需登录即可查看展台页面及产品详情。<br/>2.游客可直接询盘（询盘后登录）',
		REWARD_TIP2: '产品管理',
		TIP2_CONT1: '1、新增产品审核业务，供应商发布的产品须经过平台审核通过才能上线供买家查询。<br/>2、新增产品上下线功能，通过审核的产品，供应商可以任意设置上下线。<br/>3、新增橱窗产品设置，设置为橱窗产品将在买家搜索的结果页面当中，获得优先推荐（橱窗产品搜索结果优先显示将会在3月15日推出，供应商可先把产品预先设置，做好准备）。'
	},
	BUYER: {
		INDEX: {
			VIEW_OPP: '待处理商机',
			POST_BL: '发布采购需求',
			INFO_INTEGRITY: '信息完整度：',
			IMPROVE: '完善信息',
			SEARCH_PLD: '寻找适合您的供应商',
			OPP_TIT: 'Opportunities you may like',
			MSG_GUIDE: '来自[@]行业的[@@]向你[@@@]',
			ALL_RECOMMEND: '所有',
			TYPE_1: '推荐了产品和介绍了他们公司。',
			TYPE_2: '介绍了他们公司：',
			TYPE_3: '推荐了他们的产品：',
			TYPE_4: '打了个招呼。'
		},
		PURCHASE_PREFER: {
			TOP_TIT: '<span class="ico"></span><p class="des">提示：更详细的采购偏好让你获得更多的商机。现在马上完善让更多的供应商找到你。</p>',
			STEP_1_TIT: '<span class="ico"></span><h3>选择采购的产品分类<em class="tips">(至少选择一个，最多可以选择三个产品分类)</em></h3>',
			STEP_2_TIT: '<span class="ico"></span><h3>您期望供应商的规模</h3>',
			STEP_3_TIT: '<span class="ico"></span><h3>您期望供应商的性质</h3>',
			STEP_4_TIT: '<span class="ico"></span><h3>您喜欢的供应商参加广交会的情况如何？</h3>',
			STEP_2_1_TIT: '<span class="mrk"></span><h3>人员规模</h3>',
			STEP_2_2_TIT: '<span class="mrk"></span><h3>注册资金</h3>',
			STEP_2_3_TIT: '<span class="mrk"></span><h3>年营业额</h3>'
		},
		SEARCH: {
			TYPE: "分类：",
			TAG: "我的标签：",
			SOURCE: "来源："
		}
	},
	CATE_SELECTOR: {
		TITLE: '选择产品分类',
		SELECTED: '已选：',
		RETURN_TREE: '返回分类列表',
		SAVE: '保存'
	},
	PUSH_WINDOW: {
		PUSH_TIT: '推送信息',
		TEXT_PLACE: '请用英文输入，简单介绍公司情况，突出买家感兴趣的内容信息：如主营产品、出口市场等！',
		YOU_SAY: '建议结合 <strong>[@]</strong> 的行为介绍自己的情况和产品信息：',
		YOU_SHARE: '您可以向 <strong>[@]</strong> 分享您一个产品。',
		SHARE_COINS: '本次信息推送需花费 <em>[@]个C币</em>，系统升级促销期间，C币推送免费。',
		PUSH_SUCCESS: '推送信息发送成功！',
		REPEAT_PUSH: '请不要重复推送！'
	},
	MESSAGE_WINDOW: {
		WRITE_TIT: '发送邮件',
		READ_TIT: '查看邮件',
		REPLY_TIT: '回复邮件',
		INQUIRY_TIT: '发送询盘',
		SUBJECT: '标题：',
		TO: '收件人：',
		CONTENT: '内容：',
		SUBJECT_PH: '请填写一个邮件标题',
		FROM: '发件人：',
		TIME: '日期：',
		REPLY: 'Re: ',
		DEL_TIPS: '邮件已移至垃圾箱！',
		QUICK_RE_TIPS: '回复邮件成功！',
		INQUIRY_SUBJECT: '我对你的[@]感兴趣',
		QUICK_RE_PD: '在此快速回复信息，按回车发送'
	},
	INFO_WINDOW: {
		SUPPLIER_TIT: '供应商信息',
		BUYER_TIT: '采购商信息',
		BASE_INFO: '基本信息',
		FOLLOW: '商业跟踪',
		EVALUATE: '信用评价',
		ACTIVITY: '动态',
		PREFERENCE: '我的偏好',
		BUYER_PROFILE: '采购商个人信息',
		SUPPLIER_PROFILE: '供应商个人信息',
		COMPANY_PROFILE: '公司信息',
		GENDER: '性别：',
		POSTS: '职位：',
		EMAIL: '邮箱：',
		PHONE: '电话：',
		FAX: '传真：',
		ADDRESS: '地址：',
		ZIP: '邮编：',
		SKYPE: 'Skype：',
		TELEPHONE: '联系电话',
		COMPANY: '公司：',
		TYPE_BUYER: '买家类型：',
		NATURE_BUYER: '买家性质：',
		ESTABLISHMENT_TIME: '成立时间：',
		EMPLOYEES: '企业人数：',
		ANNUAL: '年采购额：',
		TYPE_SUPPLIER: '公司类型：',
		MAIN_PRODUCT: '主营产品：',
		STAFF: '人员规模：',
		REGISTERED: '注册资金：',
		PRIVACY: '<span class="ico"></span><p class="des">买家设定了[@]的部分联系方式为隐私。现在就<a href="javascript:;" action="push">推送信息</a>，建立第一次联系吧！这次推送将会耗费[@@]个C币。</p>',
		PRIVACY_APPLY: '<span class="ico"></span><p class="des">买家设定了[@]的部分联系方式为隐私。<a href="javascript:;" action="say">马上跟[@@]聊天</a>，申请让[@]针对我本人公开联系方式吧！</p>',
		APPLY_TIPS: '你正在申请查看[@]的私人信息，你可以在下面输入对话。',
		APPLY_MALE: '他',
		APPLY_FEMALE: '她',
		REMARKS: '标记：',
		GROUP: '分组：',
		ADD_TO: '添加到',
		ADD_CONTACT_TIPS: '已添加为联系人！',
		SAVED: '保存成功！',
		BUYER_INFO_TIT: '采购商信息',
		MATCH: '匹配度：',
		MATCH_PRO: '产品维度',
		PRO_TITLE: '产品匹配度：',
		MATCH_BG: '背景维度',
		BG_TITLE: '背景匹配度：',
		MARKET: '地区: ',
		PART: '参展次数: ',
		NATURE: '公司性质: ',
		LATELY: '最后参会情况: ',
		TYPE: '公司类型: ',
		SKU_TITLE: '在广交会展会现场登记的产品焦点',
		ACTIVITY_TITLE: '所有动态',
		ACTIVITY_EMPTY: '该采购商暂时没有动态',
		BOOTH_CLEANUP: '现场展位图片',
		TAB: {
			PRODUCT: '产品',
			CONTACT: '联系方式',
			INTRO: '公司介绍',
			BOOTH: '展位参观'
		},
		FEMALE: '男',
		MALE: '女',
		BRAND_EXP: '品牌经验：',
		BOOTH_TIT: 'We exhibit on October Canton Fair',
		BOOTH_TIPS: '[@]届展位摊号：',
		PHASE: '[@]期：',
		NOT_PRODUCT: 'It seems that the supplier has not prepared their product display yet.',
		NOT_INTRO: 'It seems that the supplier has not prepared their introduction yet.',
		NOT_BOOTH: 'It seems that the supplier has not prepared their booth information yet.',
		SUGGEST_ACTION: 'Click  the button <a href="javascript:;" role="contact">View Contact</a> to make contact directly!',
        VERIFY_TIPS_NOTE: '提示: ',
        VERIFY_TIPS_UNV: '该采购商审核中.',
        VERIFY_TIPS_DIS: '该采购商审核未通过.'
	},
	POST_BUYING_LEAD: {
		ATTENDING: "Attending Canton Fair: ",
		NOT_THIS_YEAR: "No, not this year.",
		I_AM_HERE_NOW: "Yes, I am here now.",
		IN_THIS_APRIL_OCTORBER: "Yes, in this April or Octorber.",
		RECEIVE_FEEDBACKS: "Receive Feedbacks",
		CHECK_EMAIL: "Check the feedbacks by email or e-cantonfair.com",
		GET_RECOMMENDATIONS: "Get Recommendations",
		GET_REC_BY_EMAIL: "Get recommendations by email",
		TELL_US_WHAT_YOU_NEED: "Tell us what you need",
		LEARN_MORE: "Learn More &gt;&gt;",
		TITLE: "发布采购需求",
		PRODUCT_NAME: "产品名称：",
		DETAIL: "详细描述 :",
		THIS_QUANTITY: "本次采购数量：",
		YEAR_QUANTITY: "年采购量：",
		DATE_LIMIT: '有限期限：',
		TRANSPORT: "运输方式：",
		FIRST_PRICE: "首选价格：",
		DESTINATION: "到达港：",
		PAYMENT: '付款方式：',
		SUPPLIER_TYPE: '供应商要求：',
		CONDITION_1: "广交会参展商",
		CONDITION_2: "有品牌合作经验",
		HOPE_RECEIVE: '期望收到：',
		DETAIL_MENU: "详细规格/目录",
		DETAIL_PRICE: "详细价格列表",
		CERT: '认证证书',
		OTHER: '其他',
		MORE_INFO: '更多的附加信息',
		TIPS: 'Complete trade information can help buyers to make better purchasing decisions.',
		NON_REQUIRED: 'non-required',
		UNIT: 'Unit type',
		ATTACH_TIPS: 'Maximum of <em>3</em> attachments(<em>2MB</em>/each, <em> doc,docx xls,xlsx, ppt,pptx, txt, pdf</em> supported)',
		UPLOAD_TIPS: '支持的格式：<em>jpg/jpeg, gif, png,doc/docx,xls/xlsx,ppt,pdf</em>；每个最大不超过2Mb',
		LETTER_TIPS: '消息应该包含20-8000个字符',
		PRODUCT_DESCRIPTION_TIPS:'您可以输入:<br> &nbsp;&nbsp;- 准确产品名称<br>&nbsp;&nbsp;- 尺寸<br>&nbsp;&nbsp;- 等级/质量标准 <br>&nbsp;&nbsp;- 材质 <br> &nbsp;&nbsp;- 用途 <br> &nbsp;&nbsp;- 包装 <br> &nbsp;&nbsp;- 其他与您产品相关的规格',
		PER: 'per'
	},
	FAVORITE: {
		ALREADY_ADDED: '该标签已添加'
	},
	CALENDAR: {
		CURRENT: '[@]年[@@]月',
		BUTTON_TEXT: ['↑', '←', '→', '↓'],
		WEEK: '日 一 二 三 四 五 六'
	},
	TPL_SHOWROOM: {
		COMP_NAME: '公司名称',
		ESTABLISHED: '成立',
		VERIFIED: '已认证',
		MPC: '主要产品类别',
		COMP_TYPE: '公司类型',
		REGION: '国家/地区',
		ADDRESS: '地址',
		ZIP_CODE: '邮编',
		NOE: '员工人数',
		REG_CAP: '注册资本',
		BUS_LICE: '营业执照',
		WEBSITE: '网站',
		COMP_INTRO: '公司简介',
		SLOGAN: '口号',
		BRIEF_INTRO: '简要介绍',
		CHAR_LEFT: '剩余字符',
		CONTACT_INFO: '联系方式',
		TEL: '电话',
		FAX: '传真',
		MOBILE: '手机',
		SKYPE: 'Skype',
		FACEBOOK: 'Facebook',
		VI_PRE: '公司展示',
		COMP_LOGO: '公司标志',
		UPLOAD_LOGO_FORMAT: '支持最大<em>1MB</em>的<em>Jpg, Gif 和 Png</em>图片格式，建议图片尺寸为<em>120*70</em>',
		COMP_TOUR: '公司视频',
		UPLOAD_VIDEO_FORMAT: '支持最大 <em>30MB</em> 的FLV视频格式，视频长度不超 <em>60</em> 秒',
		COMP_VISION: '公司形象',
		UPLOAD_IMAGE_FORMAT: '支持最大 <em>1MB</em> 的 <em>Jpg, Gif, Png</em>图片格式，最多上传8张',
		FACTORY_SIZE: '厂房面积',
		ODM_EXPERIENCE: 'ODM 经验',
		OEM_EXPERIENCE: 'OEM 经验',
		EXPERIENCE_OUTLINE: '经验纲要',
		ENGINEER_TOTAL: '工程师数',
		RDS_TOTAL: '研发人员数',
		QCS_TOTAL: '质检人员数',
		CERT: '证明',
		REQUIRE: 'This field is required.',
		PBOYE: '请简述项目经验',
		MAIN_TARGET_MARKET: '主要出口市场',
		DELIVERY_TERMS: '接受交付条款',
		PAYMENT_ACCEPTABLE: '接受交易货币',
		PAYMENT: '付款方式',
		LOADING_PORT: '离岸港口',
		LEAD_TIME: '交货期限',
		SAMPLE_AVAILABLE: '是否可寄样品',
		DAY: '天',
		SAVE: '保存',
		YES: '是',
		NO: '否',
		SQUARE_METER: '平方米',
		INDUSTRY: '行业',
        MANUFACTURER: '生产企业',
        TRADING:'外贸企业',
        MANUFACTURE_TRADING:'工贸企业',
        DOMESTIC:'内贸企业',
        OTHERS:'其他企业',
        SELECTED: "请选择列表",
        BELOW_100:'100人以下',
        PEOPLE_499:'100-499人',
        PEOPLE_999:'500-999人',
        PEOPLE_999:'1000-4999人',
        OVER_5000:'5000人及以上'
	},
	cclick: {
		l1: '您发布的采购需求',
		l2: '采购需求',
		l3: '产品的图像或更清晰的产品',
		l4: '采购量的要求',
		l5: '应用范围和功能',
		l6: '材料/材质',
		l7: '更多产品细节，如规格，认证等',
		l8: '采购商背景',
		l9: '希望@提供更多...',
		l10: '你想了解@的其他什么信息呢？ （请最多选4项）',
		l11: 'C-Click, your handy tool to request buyer to provide more details.',
		l12: '知道了',
		l13: '请至少选择一项',
		l14: '请不要选择超过 @ 项。',
		l15: "发送成功!",
		l16: '买家',
		l17: '卖家',
		l18: '这条 LeadEXpress',
		l19: 'Relevant Product Image',
		l20: 'Technical Data & Specifications',
		l21: 'Price List',
		l22: 'Certifications',
		l23: 'Export Experience on Relative Products',
		l24: 'Background Info & Brand Experience',
		l25: '点击查看更多细节'
	}
};
