/**
 * Can Message英文配置文件
 * @since: 2013-01-08
 */

Can.msg = {
	ERROR_TEXT: {
		ERR_ABNORMAL: 'Oops...something wrong here. Please try sign in again.',
		ERR_NORMAL_000: ':( Sorry, I can\'t do now. Please try again later.<br />Contact us call tel:4006-280-333',
		ERR_LOGIN_000: 'System error, please try it again.',
		ERR_LOGIN_001: 'Email/Member ID is incorrect.',
		ERR_LOGIN_004: 'Your account has been banned.',
		ERR_LOGIN_010: 'You can\'t use cantonfair id to login.',
		ERR_LOGIN_011: 'Your account has not been activated.',
		ERR_LOGIN_013: 'Your membership has expired, please renew your plan.',
		ERR_LOGIN_014: 'You don\'t have to buy any package.',
		ERR_LOGIN_021: 'Email not verified, you can not use mail login.',
		ERR_LOGIN_100: 'Sorry, The ID or password is incorrect.',
		ERR_UPLOAD_000: 'upload failed, please try again.',
		ERR_UPLOAD_100: 'files queue limit exceeded.',
		ERR_UPLOAD_110: 'file size exceeds limit.',
		ERR_UPLOAD_120: 'can\'t upload zero byte file.',
		ERR_UPLOAD_130: 'invalid file type.',
		ERR_UPLOAD_1100: 'nothing uploaded.',
		ERR_UPLOAD_1200: 'not acceptable this file type.',
		ERR_UPLOAD_1300: 'file size exceeds server limit.',
		ERR_UPLOAD_1600: 'parametric invalid, please contact administrator.',
		ERR_EMAIL_000: 'email content is not right.',
		ERR_EMAIL_101: 'subject is require.',
		ERR_EMAIL_201: 'not select contacter.',
		ERR_EMAIL_301: 'content is require.',
		ERR_PUSH_201: 'Please select a product which you want to share!',
		ERR_TREE_000: 'select too more.',
		ERR_TAG_001: 'remark can\'t empty.'
	},
	VALIDATOR: {
		MIN_TIP: 'Not less than %s characters;',
		MAX_TIP: 'No more than %s characters'
	},
	UPLOADER: {
		DRAG_TIPS: 'Drag and drop, automatic upload'
	},
	TEXT_BUTTON_VIEW: {
		REQUEST: 'This field is required.',
		LONG_LIMIT: '* Not more than 50 characters.',
		NUMBER: '* Numbers only',
		PHONE_ZONENUM: '* Numbers only (Not more than 3 characters) ("+" sign optional)',
		PHONE_CODE: '* Numbers only (Between 1 or 4 characters)',
		SIXFOUR: '* Numbers only (Not more than 64 characters)',
		ONLY_PHONE: '* Mobile phone must be 11 characters',
		EMAIL: '* Invalid email address',
		TOLONG_LIMIT: '* Not more than 128 characters',
		SEETING_TIME: 'dateFmt:HH:mm',
		PASSWORD_NOLIMIT: '* (A-Z, a-z, 0-9)',
		URL: '* Invalid URL',
		COMFIRM_PASSWORD: '* These passwords don\'t match. Try again?',
		LIMIT32: '* Not more than 32 characters',
		NOTWOFI: '* Not more than 256 characters',
		LIMIT16: '* Numbers only (Not more than 16 characters)',
		CHECK_PASSWORD: 'The password you gave is incorrect',
		PASSWORD: '* Between 6 and 20 characters (A-Z, a-z, 0-9)',
		LIMIT50: '* Between 3 and 50 characters (A-Z, a-z, 0-9)',
		ONLY_ENGLISH: '* English only. ',
		CHECK_ACCOUNT: 'The account already exists',
		SKYPE_ERROR: 'Between 6 or 32 numbers or letters,and must start with a letter'
	},
	APP_TITLE: {
		SUPPLIER: 'E-CantonFair - Supplier Platform',
		BUYER: 'E-CantonFair - Buyer Platform',
		EXPRESS: 'E-CantonFair - Express Platform'
	},
	AJAX_ERROR: '<strong style="font-weight: bold;">AJAX Error!</strong><br>URL: [@]<br />Message: [@@]',
	CHAR_LEFT: 'Characters left',
	PAGE_COUNT: '[@] total',
	ALL: 'All',
	PAGE: {
		HOME: 'Home',
		END: 'End'
	},
	BALANCE: 'C coins Balance',
	MEMBER_LEVEL: {
		'1': 'Experience',
		'2': 'Basic',
		'3': 'Premium',
		'4': 'Professional',
		'7': 'Diamond',
		'8': 'Platinum',
		'9': 'Express',
		'10': 'Presell',
		'11': 'Cloud',
		'12': 'Basic',
		'13': 'E-exporter',
		'14': 'Professional',
		'15': 'Advanced',
		'16': 'Premium',
		'17': 'Presell E-exporter',
		'18': 'VIP Member of Wuxi Commercial Bureau Project',
		'L1': 'Account',
		'L2': 'Plan',
		'L3': 'Expired',
		'L4': 'C Coins',
		'L5': 'Remaining',
		'L6': 'Used'
	},
	CATEGORY: 'Category',
	NEED_COINS: 'Need <em>[@]</em> C coins',
	COINS_NOT_ENOUGH: 'Notice: The C coins currently used to push is <em>[@]</em> Please call the Num:<em>4008517517</em>',
	MATCH_TIPS: 'Want to improve your relevance effect? <a class="mdi-pref" href="javascript:;">Modify your preference</a> or <a class="add-pro" href="javascript:;">add more products</a> to help us learn more about you now!',
	CREDIT_NOW: 'Credit Now!',
	ATTACH_FILE: 'Attachments',
	NOT_MATCH_BUYER: 'Sorry, we haven\'t found relevant buyers you need',
	NOT_MATCH_BUYER_SUGGEST: 'It’s recommended that you search buying lead',
	FAILED: 'operation failed',
	DELETE_CONFIRM: 'Do you want to delete your selected item(s)?',
	CHANGE_CONFIRM: 'Do you give up this change?',
	DOWNLOAD: 'Download',
	PRICE: 'Price',
	PRIVACY: {
		'PUBLIC': 'public',
		SECRET: 'private'
	},
	CAN_TITLE: {
		INQUIRY: 'Inquiry',
		CHAT: 'Chat Now',
		FAV: 'Collect',
		EXP_NUM: '[@] time(s) in Canton Fair',
		BUSINESS_FOLLOW: 'Followup',
		CONTACT_CUSTOMER: 'Contact',
		MATCH: 'Matching rate with my business rules [@] Relevance to My Preferences',
		CF_LEVEL: 'Buyer credit degree of Canton Fair [@] Credit Degree',
		SINO_RATING: 'Buyer SinoRating Credit Rating',
		NEW_PRODUCT: 'new product',
		BACK: 'Back',
		MODIFY: 'Edit',
		COPY: 'Copy',
		OFFLINE: 'Off shelf',
		ONLINE: 'On shelf',
		DELETE: 'Delete',
		VALID_EMAIL: 'Buyer has registered with mail address',
		VALID_PHONE: 'Buyer has registered with phone',
		HOW_COUNT: 'Match Relevance depends on your preference setting and product coverage. It\'s recommended to modify your preference or add more products to improve the relevance effect.'
	},
	DATETIME: {
		TODAY: 'Today',
		BEFORE_MIN: 'm ago',
		BEFORE_SEC: 's ago'
	},
	ACCOUNT_MENU: {
		PROFILE: 'Personal Profile',
		CHANGE_PWD: 'Change Password',
		SET_BUSS: 'Preference Setting',
		LOGOUT: 'Sign Out'
	},
	RULE_STEP: {
		BACK: 'Back',
		NEXT: 'Next',
		DONE: 'Done'
	},
	IM: {
		YOURSELF: 'Yourself',
		CHAT_NOW: 'Chat Now',
		OFFLINE: 'Offline'
	},
	//
	LOADING: 'Loading...',
	PURCHASE: 'Purchase',
	MATCH: 'Relevance',
	CREDIT: 'Credit',
	NOT_RELATED_PROD: 'Not any products.',
	NOT_SEARCH_RESULT: 'No match result for your keyword.',
	NOT_SEARCH_SUGGEST: 'Please make sure that all words are spelled correctly or try  another keyword.',
	NOT_COLLECTION: 'Sorry, you haven\'t created your Collections list.',
	NOT_COLLECTION_SUGGEST: 'Just add suppliers or products to your list now by searching.',
	NOT_ACTIVITY: 'Sorry, we haven\'t find the buyers\' activities you need, we suggest you:',
	NOT_ACTIVITY_SUGGEST: 'Automatically search the buying lead you need, and contact with them immediately.',
	PLEASE_LOGIN: 'Please Login',
	CANTON_FAIR_ID: 'Canton Fair ID or Email:',
	PASSWORD: 'Password:',
	CODE: 'Code:',
	CODE_ERROR: 'Verification code error!',
	CODE_REFRESH: 'Refresh',
	REMEMBER_ME: 'Remember me',
	FORGOT_PASSWORD: 'Forgot password?',
	NOT_MEMBER: 'I\'m not a member ',
	SIGN_UP: 'Register >>',
	FROM: 'from',
	REQUIRE_ACCOUNT: 'Please input your account!',
	REQUIRE_PASSWORD: 'Please input your password!',
	PRODUCT_LABEL: 'Product',
	SUPPLIER_LABEL: 'Supplier',
	CHINA: 'China',
	BUTTON: {
		TOP_BAR_1: {
			HOME: 'Home',
			SHOWROOM: 'My Showroom',
			MSG_CENTER: 'Message',
			CUSTOMER_MANAGE: 'Contacts',
			SETTING: 'Settings',
			SWITCH_EN: 'EN',
			SWITCH_CN: '中文',
			LANGUAGE: 'Language',
			LANGUAGE_EN: 'English',
			LANGUAGE_CN: '简体中文'
		},
		TOP_BAR_2: {
			//supplier
			MATCH_BUYER: 'Match Buyers',
			ACTIVITY: 'Activities',
			BUYING_LEAD: 'LeadEXpress',
			PRODUCT_FORM: 'Add Products',
			MANAGE_PRODUCT: 'Manage Products',
			PRODUCT_COUNT: 'Statistics',
			CAR_COUNT: 'Express Data',
			EXC_COUNT: 'SourcingEgg Data',
			SHOWROOM: 'Showroom Info',
			//buyer
			MY_ROOM: 'Exclusive Channel',
			SEARCH: 'Search',
			COLLECTIONS: 'Collections',
			MANAGE_BL: 'Manage LeadEXpress',
			POST_BL: 'Post LeadEXpress'
		},
		SEARCH_BTN: 'Search',
		SEARCH_BL: 'Search LeadEXpress',
		CONTACT_BTN: 'Contact Now',
		VIEW_NOW: 'View Now',
		VIEW_ACTIVITY: 'Buyers Activity',
		RETURN_LIST: 'Back',
		MY_ACTIVITY: 'Relevance Activities',
		ALL_ACTIVITY: 'All Activities',
		SIGN_IN: 'Sign In',
		BR_PREV: 'Back',
		BR_NEXT: 'Next',
		BR_DONE: 'Done',
		INQUIRY: 'Inquiry',
		FAV: 'Collect',
		ADD_NOW: 'Add Now',
		ADD_Btn: 'Add To',
		ADD_MORE_PRODUCT: 'Add Now',
		RELATED_PRODUCT: 'Related Product',
		//
		DATA_IDENT: {
			ITEM: 'items',
			INQUIRY: 'Inquiry',
			ACTIVITY: 'Activities',
			ACT_TIPS: 'Buyer activities recently.',
			PRODUCT: 'Product',
			PRO_TIPS: 'Products posted up to date.',
			BUYING_LEAD: 'LeadEXpress',
			BL_TIPS: 'LeadEXpress unread up to date.',
			OPP: 'Collections',
			INQ_REPLY: 'Inquiry Replies',
			BL_REPLY: 'LeadEXpress Replies'
		},
		SELECT: 'Select',
		RESELECT: 'Reselect',
		DEL_PUSH_PRO: 'Delete',
		DEL_MSG: 'Delete',
		CONTACT_NOW: 'Contact Now',
		PUSH_INFO: 'Push Info',
		PUSH_INFO_TO_HIM: 'Push Info To Him',
		ADD_CONTACT: 'Add to Contact',
		VIEW_DETAIL: 'View Detail',
		SEARCH_NOW: 'Search',
		SEND: 'Send',
		SURE: 'Sure',
		CANCEL: 'Cancel',
		UPLOAD: 'Upload',
		SAVE: 'Save',
		EDIT: 'Edit',
		REPLY: 'Reply',
		DELETE: 'Delete',
		SEARCH: 'Search',
		RESTORE: 'Restore',
		NEW_GROUP: 'Create Group',
		OK: 'OK',
		YES: 'Yes',
		NO: 'No'
	},
	CREDIT_RATING: {
		AAA: 'Very strong strength, very high resistance to risk, excellent credit status',
		AA: 'Strong strength, high resistance to risk, good credit status',
		A: 'Relatively strong strength, relatively high resistance to risk, normal credit status',
		BBB: 'Average strength, average resistance to risk, acceptable credit status',
		BB: 'Below-the-average strength, below-the-average resistance to risk, less acceptable credit status',
		B: 'Relatively weak strength, relatively low resistance to risk, passable credit status',
		CCC: 'Weak strength, low resistance to risk, relatively poor credit status',
		CC: 'Very weak strength, very low resistance to risk, poor credit status',
		C: 'On the verge of bankruptcy, basically discredited',
		NR: 'Subject is not rated because it is established for no more than one year or it goes out of business or information is not enough',
		L1: 'Overseas buyers credit report',
		L2: 'To buy the report, please provide us the buyer\'s company name and the registered address',
		L3: 'Buy Now',
		L4: 'Shop Process',
		L5: 'STEP',
		L6: 'Preview reports',
		L7: 'Contact us',
		L8: 'Receive email with reports'
	},
	FORM: {
		SELECT_NORMAL: '-- Please Select One Item --',
		PRIMARY_KEYWORD: 'Primary keyword',
		KEYWORD: 'Keywords'
	},
	SERVICES: {
		MENU_TITLE: 'Trade Services',
		ZHONG_XB: 'Credit Insurance',
		ZHONG_YTB: 'Easy Financing',
		CARD_PAY: 'Cross Border Payment'
	},
	MODULE: {
		BUYING_LEAD: {
			TITLE: 'LeadEXpress',
            TITLE_LINK: 'View more LeadEXpress from the buyers in <a style="color: #4db07a;" href="%s" target="_blank">Sourcing LeadEXpress</a>.',
			ALL_BL: 'Recommended LeadEXpress',
			MY_BL: 'Quoted LeadEXpress',
			UNVERIFY_BL: 'Unverified Buyers LeadEXpress',
			ALL_LABEL: 'Matched LeadEXpress',
			CATE_LABEL: 'Category',
			REGION_LABEL: 'Region',
			TIME_LABEL: 'Latest',
			TIME_ITEM: ['Not limited', 'Within one week', 'Within one month', 'Within three months'],
			CATEGORY: 'Category: ',
			QUANTITY: 'Quantity Required: ',
			TIME_LEFT: 'Time Left: ',
			OFFLINE_TIME: 'Offline Time: ',
			POST_DATE: 'Date Posted: ',
			SECRET: 'Keep secret',
			NOT_MATCH_BL: 'Sorry, no results found. ',
			NOT_MATCH_BL_SUGGEST: 'It\'s suggested you search your target buyers and send him/her push info.',
			PUSH_SUGGEST: 'Or via browsing buyers\' business activities to find their prior need , and push your information to them immediately.',
			SUBJECT_PLACEHOLDER: 'Re: [@] Feedbacks from [@@]',
			REPLY_TIT_ERROR: 'Title cannot be more than 50 characters',
			REPLY_CON_ERROR: 'Content cannot be more than 8000 characters',
			REPLY_EPT_ERROR: 'The title and content are required.',
			ATTACHMENT: 'Attachment',
			READ: 'Read',
			UNREAD: "UnRead",
			SUCCESS: 'Success',
			THIS_CANTON_FAIR: '114th session LeadEXpress posted by applicant buyer.',
			SCENE_CANTON_FAIR: '114th session LeadEXpress, receieved by Cantonfair-elite on site.',
			MY_FAVORITE: 'My Collection',
			LIEV_LEADEXPRESS: 'Canton Fair Onsite LeadEXpress',
			LEADEXPRESS: 'Canton Fair Pre-Matching LeadExpress',
			MATCH: 'Matched LeadEXpress',
			EMPTY: 'Empty',
			POST_TIME: 'Post time',
			TIP_MAX_SELECT: 'Select up to %s',
			COMING_EXPIRED: 'Coming Expired',
			SUBMIT: 'Submit',
			CLEAR_ALL: 'Clear all',
			SELECTED: 'Selected :',
			COLLECTION_TIP: 'Put it into your collection, read it anytime from "Type" selector.',
			MORE_TIP: 'View More LeadEXpress',
			ALL_TYPE: 'All type',
			RECOMMEND: 'Recommended',
			AUTHORIZED: 'Authorized Buying Leads',
			REWARD: 'Reward',
			REWARD_TIPS: 'You have the opportunity to award when you reply this LeadEXpress.',
			VIEW_NOW: 'View Detail',
			DIALOGUE_REFERENCE: 'Example for the conversation between buyer consultant and global buyer (click to enlarge the picture)',
			EXPORT: 'Export Market: ',
			ORDER_DATE: 'Expect Order Date',
			SCHEDULE: 'Recent Purchasing Schedule in China',
			COMP_INTRO: 'Company Introduction: ',
			YEAR_ESTABLISH: 'Year Established: ',
			COMP_WEBSITE: 'Company Website: ',
			OTHER_CONTACT: 'Other Contact',
			SUCCESS_REPLY: 'Reply the Inquiry Successfully!',
			TIPS: 'We highly recommend you contact the buyer via email or instant messaging tool when replying the inquiry!',
			VIP_BUYING: 'Authrized Buying Leads',
			PRODUCT: 'Product picture(click to enlarge the picture): ',
			MORE_INFO: 'More trade information and requirements',
			FAX: 'fax: ',
			COMPANY: 'company: ',
			REPLY_SUCC_CON: '<div class="reply-succ"><h4><i class="icons current"></i>&nbsp;&nbsp; Reply the Inquiry Successfully!</h4><p>We highly recommend you contact the buyer via email or instant messaging tool when replying the inquiry!</p></div>'

		},
		CF_BUYER_INFO: {
			CONTACT: 'Contact',
			COUNTRY: 'Country',
			COMPANY: 'Company',
			EMAIL: 'Email',
			TELEPHONE: 'Telephone',
			FAX: 'Fax',
			ADDRESS: 'Address',
			CONTACT_TIT: 'Contact Now!'
		},
		BUYER_ACTIVITY: {
			TITLE: 'Buyer Activities',
			CATEGORY: 'Category',
			COUNTRY: 'Country/Region',
			ACTION_TYPE: 'ActionType',
			LATEST: 'Latest',
			LOAD_MORE: 'View More Activities'
		},
		BUSINESS_SET: {
			TITLE: 'Tips: For precisely matching, please customize your targeting preference on your own situation.',
			STEP1_TITLE: 'Industry you are devoted in <em class="tips">Maximum 2 industries</em>',
			STEP2_TITLE: 'Your main product range <em class="tips">Maximum 40 categories</em>',
			STEP3_TITLE: 'Your target market',
			STEP3_TITLE_1: 'Target Area <em>(Maximum 12)</em>',
			STEP3_TITLE_2: 'Target Counties/Regions <em>(Maximum 20)</em>',
			ERROR_1: 'Sorry, no choosing more than [@] industries.',
			ERROR_2: 'that is require.'
		},
		PRODUCT_FORM: {
			TITLE: 'Add Products',
			TIP: 'Please fill in the fields as below.',
			TITLE_1: 'Basic Info',
			EXR_TIPS_1: 'A highly completeness of your product infomation can help to build up a full business image while lead to a higher search ranking.',
			PRODUCT_NAME: 'Product Name: ',
			PRODUCT_MODEL: 'Model: ',
			PRODUCT_VIDEO_URL: 'Video Link: ',
			//PLACEHOLDER: 'Please Enter Product Name',
			CATEGORY: 'Category: ',
			PRIMARY_KEYWORD:'Primary Keyword: ',
			KEYWORD: 'Keywords: ',
			PHOTO: 'Product Photos: ',
			ATTACHMENT: 'Attachment: ',
			UPLOAD: 'Upload',
			UPLOAD_TIPS: 'Format:<em>jpg/jpeg, gif, png</em>; Each Maximum Size:3MB; Suggest Picture Size:<em>600*600</em> pixels',
			NEW_PRODUCT: 'New Product: ',
			GROUP: 'Group: ',
			TITLE_2: 'Specifications',
			EXR_TIPS_2: 'Comprehensive and in-depth description is usually eye catching to bring you more chances.',
			INTRO: 'Brief Description: ',
			SPEC: 'Specifications: ',
			TITLE_3: 'Trading Info',
			EXR_TIPS_3: 'A profile with trading information can enhance possiblity to catch target buyers.',
			QUANTITY: 'Minimum Order Quantity: ',
			SUPPLY: 'Monthly Capacity: ',
			PRICE: 'FOB Price: ',
			PORT: 'Loading Port: ',
			PAYMENT: 'Payment Terms: ',
			COUNT_LETTER: '[@] left, Maximum of 250 characters',
			REQUIRE: 'This field is required.',
			VIDEO_URL_TIPS: 'Product Video\\:<br/>* Please upload product introduction video here, English dubbing and subtitling are preferred.<br/>* The video should mainly contain product introduction, such as product type, manufacture process, product certificates, patents, etc.<br/>* Video quoted from oversea main media platform, like YouTube, metacafe，video google ect, is highly recommended, while those from external URL of other e-Commerce website is not welcome.',
			VIDEO_URL_FILTER_TIPS: 'Video quoted from oversea main media platform, like YouTube，metacafe ，video google ect, is highly recommended, while those from external URL of other e-Commerce website is not welcome.',
			INVALID_URL_TIPS: 'Incorrect Video URL',
			NON_CHINESE: 'Please input the information in English.',
			LETTER_TIPS: '10-150 characters',
			selectProduct: 'Please select a category',
			PRIVACY_STE: 'Privacy Setting',
			OPEN: 'Open',
			PRIVACY: 'Privacy',
			PRIVACY_STE_TIPS: 'Open\\: The product can be find by unknown visitors;\nPrivacy\\: The product can be find by buyers only.',
			TIPS: "To be eligible to use the service, please confirm that you are entitled to submit the information and that the information is accurate, not confidential, and not in violation of any contractual restrictions or other third party rights. Once you're violate the rules, e-Cantonfair have the authority to delete it before notice.",
			YES: 'Yes',
			NO: 'No',
			LC: 'L/C',
			TT: 'T/T',
			DP: 'D/P',
			MG: 'Money Gram',
			CC: 'Credit Card',
			PP: 'Paypal',
			WU: 'Western Union',
			CA: 'Cash',
			ES: 'Escrow',
			OT: 'Other',
			SAVE: 'Save',
			GROUP_PLACE: 'Select Group',
			GROUP_TEXT: 'Create Group',
			CREATE_GROUP_NAME: 'Input the group name',
			ERROR_TIPS: 'Grouping of repeat, please try another',
			ADD_TO: 'Add To',
			ADD: 'Add',
			MONEY_UNIT: 'Monetary unit',
			UNIT: 'Unit type',
			PER: 'per',
			PN_1: 'A straightforward product name includes<br>* Key attributes/specifications<br>* Model number<br>* Relevant report',
			RRIMARY_KEYWORD: 'Primary Keyword Tips<br>* a word/phase that best describes the product<br>* Try using category or synonym<br>* no more than 30 characters',
			KEYWORD_1: 'Keyword Tips<br>* Synonym of the product name<br>* Frequent used product name<br>* Related words',
			DETAIL_1: '* Make it as detailed as possible. The following factors might be useful<br>&nbsp;&nbsp; --feature<br>&nbsp;&nbsp; --function<br>&nbsp;&nbsp; --quality standard<br>&nbsp;&nbsp; --certifications<br>&nbsp;&nbsp; --service, and etc.<br>* Make advantage of multi-angel photos, as well as packaging, design drawing photos.<br>* Make it in a point form format.',
			/*
			 Outline your strengths & competence to attract more of your target buyers' traffic.	用一句话来展示产品卖点和竞争优势，呈现在搜索结果列表中，有效吸引买家点击发送询盘。
			 Format:Jpg/Jpeg, Gif, Png; Each Maximum Size:3MB; Suggest Picture Size:600*600 pixels	支持的格式：Jpeg, Jpg, Gif, or Png；最大不超过3Mb，建议图片大小600×600 像素
			 */
			LOAD_PORT_BAN_TXT: 'Please Enter Loading Port',
			TEXT_MIN_LEN: 'Please enter at least {0} characters',
			TEXT_MAX_LEN: 'Please enter no more than {0} characters',
			FOB_PRICE_TIPS: 'Fob price is not reasonable',
			DIGITS: 'Please enter only digits.',
			MAX: 'Please enter a value less than or equal to {0}',
			NUMBER: 'Please enter a valid number.',
			SELECT_FILE: 'select file',
			SENSITIVE_WORD: 'Your input with "@", may involve the infringement, please confirm whether to continue to submit?',
			SAME_NAME: 'You repeat the same product name and model, please describe and Optimization in accordance with the new characteristics of the product.'
		},
		PRODUCT_DETAIL: {
			MATCH: 'Relevance:',
			MAIN_PRODUCT: 'Product Range:',
			CONTACTER: 'Contact:',
			CERT: 'Certification:',
			PRICE: 'FOB Price:',
			PORT: 'Loading Port:',
			QUANTITY: 'Minimum Order Quantity:',
			ABILITY: 'Monthly Capacity:',
			PAYMENT: 'Payment Terms:',
			TAGS: 'Tags:',
			INTRO: 'Brief Introduction :',
            VIDEO_DISPLAY:'Video Display',
			SPEC: 'Specifications',
			CONTACT_NOW: 'Contact Now!',
			SUBJECT: ' Subject:',
			CONTENT: 'Message:',
			INQUIRY: 'Inquire',
			FAVORITES: 'Collect',
			ADD_TAG: 'Add Tags for this Product',
			TIP: 'You can find it from your Collections.',
			COLLECT: 'Added!',
			SUBJECT_PLACEHOLDER: 'Re: Write a Email',
			NO_PRODUCT_TIPS: 'Sorry! Can\'t found the product.<span>the product has been off-shelves.</span>',
			NO_PRODUCT_TIPS_2: '<span>10 seconds to post what you want!</span>Thousands of buyers are trying to use it,and you?',
			OR: 'or',
			POST_BL_BTN: 'Post LeadEXpress',
            VIDEO_DISPLAY:'Video Display'
		},
		MY_ROOM: {
			TITLE: 'Exclusive Channel',
			NOT_DATA_TIPS: 'Sorry, you haven\'t received any push notifications.',
			NOT_DATA_SUGGEST: 'We suggest  you search suppliers or products now.',
			LOAD_MORE: 'View More Push'
		},
		OPPORTUNITY: {
			EGG_TIP1: 'Sourcing Egg, your onsite information collector.',
			EGG_TIP2: 'Everytime you scanned the sourcing egg, the corresponding information will be saved here, so that you <br/> could check anytime, anywhere.',
			MATCH: 'Match:',
			SCAN_TIME: 'Scan time: ',
			TITLE: 'Manage Collections',
			CATEGORY: 'Type',
			TAG: 'Tag',
			PRODUCTS: 'Products',
			CONTACT: 'Contact: ',
			SOURCE: 'Source',
			HOME_TIP: 'Good job! Finally you get here.<br/> What you have scanned on the venue will be saved <a href="">here.</a>',
			COLLECTIONS: 'Collections',
			SOURCING_EGG: 'Sourcing Egg'
		},
		SEARCH: {
			TITLE: 'Search',
			CANTON_FAIR_ID: 'CantonFair ID:',
			CONTACTER: 'Contact:',
			MAIN_PRODUCT: 'Main Product:',
			MIN_ORDER: 'Min Order:',
			FOB: 'FOB Price:',
			PAYMENT: 'Payment Term:',
			SUPPLY: 'Supply Ability:',
			MGNT: 'Mgnt Certification:',
			SEARCH_NORMAL: 'Supplier',
			SEARCH_SELECT: [ 'Product', 'Supplier' ],
			SEARCH_ADV: 'Advanced Search',
			SEARCH_BACK: 'Back',
			TYPE: 'Type:',
			KEYWORD: 'Keywords:',
			INDUSTRY_TYPE: 'Industry/Category:',
			SEL_INDUSTRY: 'Please Select Industry/Category',
			SEL_COMPANY: 'Please Select Business nature',
			NOT_RELATED: 'No products temporarily',
			CFER: 'Canton Fair Exhibitor:',
			TIP: 'Search result shows according to your preset preference, including category, target market, and etc. [@]',
			VIEW_MY_PREFERENCE: 'View my preference',
			SEARCH_NOT_RESULT_TIPS: 'Want to get the matched suppliers and detailed quotations?',
			SEARCH_RESULT_PBL_ORANGE: '10 seconds to post what you want!',
			SEARCH_RESULT_PBL_BLACK: 'Thousands of buyers are trying to use it, and you?',
			SORTS_LESS: 'less',
			SORTS_MORE: 'more',
			SORT_BY: 'Sort by: ',
			PREV: 'Prev',
			NEXT: 'Next',
			HOME: 'Home',
			TOTALCOUNT_PRODUCT_INFO: 'Products',
			TOTALCOUNT_SUPPLY_INFO: 'Suppliers',
			EXHIBITOR: 'Exhibitor',
			NON_EXHIBITOR: 'Non-exhibitor',
			NARROW_DOWN_INFO: 'Narrow down results by sourcing preference',
			LEAD_EXPRESS: 'LeadEXpress',
			LEAD_EXPRESS_TIPS: 'A 1-minute way to quickly post a buying lead, and you will find the magics after it!',
			LEAD_EXPRESS_ACTION: 'Got it!',
			COMPANY_TYPE: 'Company type',
			MANUFACTURER: 'Manufacturer',
			TRADING_COMPANY: 'Trading Company',
			MANUFACTURE_TRADE_COMPANY: 'Manufacture & Trade Company',
			OTHER: 'Other',
			ADD_MORE_REGION: 'Add more Region',
			REGION: 'Region',
			EAST_CHINA: 'East China',
			NORTH_CHINA: 'North China',
			WEST_CHINA: 'West China',
			CENTRAL_CHINA: 'Central China',
			SOUTH_CHINA: 'South China',
			BOOTH_NO: '115th Booth No',
			PHASE: 'Phase',
			EXHIBITOR_NO: 'Exhibitor',
			KEYWORD_ERROR_INFO: 'Please input a search keyword',
			INQUIRY_EXHIBITOR: 'View Showroom'
		},
		MY_CONTACTS: {
			TITLE: 'My Contacts',
			ALL_GROUP: 'All Contacts',
			PRIVACY: 'Private',
			CONTACTER: 'Contact',
			MATCH: 'Relevance',
			SETTING: 'Profile Setting',
			LATEST_CONTACT: 'Latest Contact',
			OPERATE: 'Action',
			ADD_TO: 'Move To',
			GROUP_TEXT: 'Create Group',
			DEL_TIPS: 'Deleted successfully!',
			DEL_FAIL: 'Deleted fail!',
			GUEST_TYPE: 'Attributes',
			RELATIONSHIP_LEVEL: 'Relationship',
			SYMBIOSIS: 'Partnership Stages',
			VAL_ASSESSMENT: 'Value Evaluation',
			CREDIT_RATING: 'Credit Evaluation',
			PARTNER: 'Partner Ship',
			VAL_ASSESSMENT_BUYER: 'Value Assessment',
			CREDIT_RATING_BUYER: 'Credit Rating',
			EXH_DETAIL: 'Show details @',
			CLIENT_TYPE: {
				POTENTIAL: 'POTENTIAL',
				NORMAL: 'Normal',
				AGENCY: 'AGENCY',
				PERSONAL_CLIENT: 'Personal Client',
				INVALID: 'Invalid'
			},
			RELATIONSHIP: {
				CLOSE: 'Close',
				BETTER: 'BETTER',
				NORMAL: 'Normal',
				BAD: 'Bad'
			},
			COOPERATION: {
				FOLLOWING: 'Presale Following Stage',
				CONTRACT: 'Contract Stage',
				COOPERATION_STAGE: 'Cooperation Stage',
				EOF_CONTRACT: 'Expiration of Contract Stage'
			},
			ASSESSMENT: {
				VERY_HIGH: "Very High",
				HIGH: "High",
				MIDDLE: 'Middle',
				LOW: 'Low',
				VERY_LOW: 'Very Low'
			},
			CREDIT: {
				VERY_HIGH: "Very High",
				HIGH: "High",
				MIDDLE: 'Middle',
				LOW: 'Low',
				VERY_LOW: 'Very Low'
			},
			PRIVATE_OPEN: 'private info is open',
			TRACE: 'Followup',
			NOT_NULL: 'This field is required.',
			LONG: 'Too many words',
			MODIFY: 'Modified',
			MODIFY_FAIL: 'Modified Fail',
			DELETE: 'Deleted!',
			DELETE_FAIL: 'Delete Fail',
			SELECT_SOMEONE: 'Please select some contacts',
			SET_GROUP_TIPS: 'The contacter has been added to the tag.',
			VIEW_ALL: 'View All',
			NOT_CONTACT: 'Sorry, no matching results',
			TRY_AGAIN: 'Please make sure that all words are spelled correctly or try  another again.'
		},
		PRODUCT_MANAGE: {
			ON_LINE: 'On-line',
			OFF_LINE: 'Off-line',
			ALL: 'All',
			STATUS: 'Status:',
			PASS: 'Pass',
			MASK_AS: 'Mask As',
			PENDING: 'Pending',
			REJECTED: 'Rejected',
			SHOWCASE: 'Showcase',
			TITLE: 'Manage Product',
			ADD_PRODUCT: 'Add Product',
			STATE: 'View Statistics',
			MARK_NEW: 'New Product',
			MARK_FAIL: 'Setup for new product failure',
			NAME: 'Product Name',
			GROUP: 'Group',
			NOT_GROUP: 'No Group',
			LAST_MODIFY: 'Modified',
			ACTION: 'Action',
			CREATE_GROUP: 'New Group',
			EDIT_GROUP: 'Edit',
			EDIT_GROUP_FAIL: 'Edit Fail',
			DEL_GROUP: 'Delete',
			MIN_ORDER: 'Min Order:',
			FOB_PRICE: 'Fob Price:',
			PAYMENT: 'Payment Term:',
			SUPPLY: 'Supply Ability:',
			DEL_TIPS: 'Deleted successfully!',
			DELETE_FAIL: 'Delete Fail',
			MARK_SUCCESS: 'Set Successfully!',
			ADD_GROUP_PROMPT: 'The product has been added to the [@] tag.',
			CHECKED_TIPS: 'Please select product',
			ALL_GROUP: 'All Groups',
			MULTI_SET_GROUP: 'The products has been added to the [@] tag.',
			SET_GROUP_FAIL: 'Set grouping failed',
			NOT_NULL: 'This field is required.',
			LONG: 'Word too much',
			DATA_EMPTY: 'Sorry，You haven\'t add any product information',
			PRODUCT_FORM: 'Add Product',
			SEARCH_EMPTY: 'Sorry，There is no matching results:',
			SEARCH_TIPS: 'Please check the spelling of your search keywords or a new search.',
			SEE_ALL: 'Back',
			DELETE_ERROR: 'Empty the grouping of products before you delete the group.',
			NOT_SHOWCASE: 'You don\'t have permission settings showcase products, <br> please up-grade your membership package.',
			NOT_TIP: 'Don\'t show again',
			SHOWCASE_TIP: 'You can set  a total of <i>%s</i> showcase products.',
			SHOWCASE_SELECTED: 'You can also set <i>%s</i> showcase products.',
			REASON: 'Reason: ',
			SHOWCASE_MAX_TIP: 'You have %s showcase products, <br> Showcase products have exceeded limit.'
		},
		MSG_CENTER: {
			TITLE: 'Message Center',
			SELECT_LABEL: ['All', 'Read', 'Unread'],
			SEARCH_LABEL: ['All', 'Inquiry', 'Email', 'System'],
			SOURCE_LABEL: ['All', 'Inbox', 'Outbox'],
			DELETE: 'Delete',
			ADD_TO_CONTACTER: 'Add To Contacter',
			EXPORT: 'Export',
			ALL_TYPE: 'All',
			SENDER: 'Sender',
			RECIPIENT: 'Recipient',
			SUBJECT: 'Subject',
			TYPE: 'Type',
			NO_MSG: 'Sorry, no message record.',
			NO_MATCH: 'Sorry, no matching results.',
			TIP: 'Please try other keywords.',
			MY_CONTACT0R_TIP1: "Add to contacts",
			MY_CONTACT0R_TIP2: "Already in contact list",
			READ: "Read",
			NOT_READ: "Unread",
            ATTENTION:'Attention',
			TYPE1: "Inquiry",
			TYPE2: "Email",
			TYPE3: "Systems",
			NAME_P: "Business Cards",
			COMPOSE: "COMPOSE",
			INBOX: "Inbox",
			OUTBOX: "Outbox",
			SPAM: "Trash",
			RESTORE: "Restore",
			DELETE_FOREVER: "Delete Forever",
			RESTORE_SUCCESS: "Restore successfully!",
			RESTORE_FAIL: 'Restore Fail1',
			SELECTED: "Please select",
			MOVE_TRASH: "Move message to trash successfully!",
			DEL_SUCCESS: "Delete successfully!",
			ADD_CONTACT_SUCCESS: "Added to contact list successfully.",
			SEND: "The message has been sent",
			DELETE_FAIL: 'Delete Failure',
			VIEW_MORE: 'View More Detail',
			SYS_SENDER: 'E-cantonFair.com',
            UNVERIFY: 'Unverify'
		},
		SHOWROOM_SET: {
            CONFIRM_LEAVE : 'This page asks you to confirm that you want to leave - data you have entered may not be saved.',
            CONFIRM_LEAVE_YES: 'Confirm leave',
            CONFIRM_LEAVE_NO: 'Stay in the page',
            OTHER_URL_TIP: 'Enter the other platform of electronic business web site, please re - enter the website address.',
			PREVIEW: 'Preview',
			TEMPLATE_SETTING: 'Template Setting',
			HTTP_SETTING: 'Http Setting',
			COMP_INFO: 'Company Info',
			FACTORY_INFO: 'Manufacturing Info',
			MARKET_INFO: 'Trading Info',
			PRODUCT_INFO: 'Product Info',
			INFO_INTEGRITY: 'Profile Completeness',
			SHOWROOM_INFO: 'Showroom Info',
			COMP_INFO_TIPS_1: 'Fields marked with<span class="bg-ico required"></span> is required. If you want to modify the field highlighted as Verified, please contact Customer Service by <em>4006-280-333</em>',
			COMP_INFO_TIPS_2: 'Fields marked with<span class="bg-ico required"></span> is required. If you want to modify the field highlighted as Verified, please contact Customer Service by <em>4006-280-333</em>',
			COMP_INFO_TIPS_3: 'Please complete the info of the E-booth as soon as possible and submit to the audit,Make sure your  E-booth on-line successful.',
			COMP_INFO_TIPS_4: 'You have submitted your E-booth\'s info to the audit,please be patient,having any questions,please call:4006-280-333',
			COMP_INFO_TIPS_5: 'Your E-booth\'s info is be rejected,our customer service will contact with you and tell you how to modify.',
			COMP_INFO_TIPS_6: 'Your E-booth\'s info is passing.',
			AUDIT: 'Pending',
			AUDIT_1: 'Save and Submit for Review',
			MARKET_LABEL_1: 'General Performance',
			MARKET_LABEL_2: 'Export Sales',
			MARKET_LABEL_3: 'Trading Terms',
			MARKET_LABEL_4: 'Main Product',
			MARKET_LABEL_5: 'Hot Product',
			MARKET_LABEL_6: 'New Product',
			MARKET_TIPS_1: 'Details of Sales from Main Target Market:',
			NOT_SALE_RECORD: "Sorry, you don't have any performance record.",
			NOT_PRODUCT_RECORD: "Sorry, you don't have any product record.",
			FISCAL_YEAR: 'Fiscal Year',
			YEAR_INCOME: 'Annual Sales Volume',
			EXPORT_RATE: 'Export Proportion',
			YEAR_EXPORT_AMOUNT: 'Export Sales:',
			YEAR_SALE_AMOUNT: 'Annual Sales Volume',
			SALE_AREA: 'Trade Area',
			RATE_PERCENT: 'Proportion',
			MAIN_CUSTOMER: 'Main Customer',
			NEW_PRODUCT_TOTAL: 'new products in the showroom',
			PRODUCT_NAME: 'Product Name',
			PRODUCT_ACTION: 'Action',
			MIN_ORDER: 'Min Order:',
			FOB: 'FOB Price:',
			PAYMENT: 'Payment Term:',
			SUPPLY_ABILITY: 'Supply Ability:',
			OFF_STORE: 'Remove \'New\' Tag',
			MAIN_PRODUCT_CATE: '<span class="bg-ico required"></span>Main Product Category',
			SALE_PRODUCT_RATE: '<span class="bg-ico required"></span>Sales Proportion',
			SALE_PRODUCT_NAME: '<span class="bg-ico required"></span>Product Name',
			SALE_YEAR_AMOUNT: '<span class="bg-ico required"></span>Annual Sales Volume',
			SALE_MIN_ORDER: '<span class="bg-ico required"></span>Min Order Quantity',
			SALE_MAIN_CUSTOMER: 'Main Target Buyers',
			MAIN_PRO_PD: 'Add a main Product keyword',
			MAX_ITEM: 'Only allowed to enter five data',
			ADD_NOW: 'Add A New Product',
			SUCCESS: 'Success',
			FAIL: 'Fail',
			DATA_LIMIT: 'no more than 8 data',
			REQUIRE: 'Please fill the required field',
			VALID_NUMBER: 'Please enter a valid number.',
			PERCENT_NUMBER: "Please enter a number between 0 to 100",
			MAX_NUMBER_ERROR: "This number is not allowed to greater than 9,999,999,999.",
			ADD_SALES_ERROR: 'All Annual-Sales-Volume together must be less than Export-Sales-Volume',
			SAME_YEAR_ERROR: 'Can not add the same year',
			SALES_PROPORTION: 'All Sales-Proportion together must be less than 100%',
			SELECT_BLANK_TXT: '--Select--',
			MAX_MAIN_PRODUCT: 'Main Products can not more than 6.',
			MAX_PRODUCT_NAME: 'Products\'s can not more than 20. ',
			TEMPLATE: 'Template Setting',
			HTTPSETTING: 'Http Setting',
			HTTP_SERVICE: 'modify the verified information, please contact Customer Service : 400 -123-232 .',
			HTTP_NAME: 'Your Showroom Domain Name:',
			HTTP_HTTP: 'Http://',
			HTTP_COM: '.en.e-cantonfair.com',
			HTTP_NOTICES: 'Note:',
			HTTP_NOTICETIPS: '• Custom Domain Name Can NOT be re-edited after verification. Please contact Custom Service for update.<br/>• Custom Domain Name should contain more than 3 characters, only letter and number are acceptable. No specific symbol is allowed.<br/>• The following contents are not acceptable: www, Chinese Pinyin, and sensitive words.',
			HTTP_PEND: 'Under verified',
			HTTP_NOMATCH: 'Incorrect site. ',
			HTTP_SET: 'Please submit again.',
			TEMPLATE_TIPS1: 'Column marked with<span class="bg-ico required"></span>are required. You could adjust the column order with<span class="icons arrow-6"></span>',
			TEMPLATE_EDIT: 'Modify',
			TEMPLATE_BANNER: 'Customize hero banner (Main page full measure slider)',
			TEMPLATE_NOTICE: 'Note:',
			TEMPLATE_BANNER_TIPS: 'It concludes full measure slider and showcase slider.',
			TEMPLATE_BOOTH: 'Canton Fair on site booth stand',
			TEMPLATE_BOOTH_TIPS: 'It will be displayed if you did attend the show. Otherwise, it\'s hidden.',
			TEMPLATE_YES: 'On show',
			TEMPLATE_NO: 'Off',
			TEMPLATE_COMPANY: 'Company information',
			TEMPLATE_COMPANY_TIPS: 'It will be displayed according to your profile. Your current information completeness is <span class="orange">%s</span>, please improve your information.',
			TEMPLATE_CHANNEL: 'Window products',
			TEMPLATE_CHANNEL_TIPS: 'Your current window products：<span class="orange">%s</span>,(Maximum at <span class="orange">%s</span>)',
			TEMPLATE_CHANNEL_TIPS2: 'Suggest:',
			TEMPLATE_CHANNEL_TIPS3: 'Your current package has no permission to add window products. <a class="green" target="_blank" href="http://zh.e-cantonfair.com/custom-service">Add window products now!</a>',
			TEMPLATE_CHANNEL_TIPS4: 'Your current window products: <span class="orange">%s</span> , (Maximum at <span class="orange">%s</span>)，<a class="green" href="#!/product-manage">Add new window products now!</a>',
			TEMPLATE_NEWPRODUCT: 'New products',
			TEMPLATE_NEWPRODUCT_TIPS: '该模块自动读取最新%s个新品标签的产品信息。',
			TEMPLATE_NEWPRODUCT_TIPS2: 'Your current new products: <span class="orange">%s</span>. (Maximum at 12)',
			TEMPLATE_NEWPRODUCT_TIPS3: 'Your current new products: <span class="orange">%s</span>. (Maximum at 12) , <a class="green" href="#!/add-product">Add new products now!</a>',
			TEMPLATE_MAINPRUDTCTS: 'Main products',
			TEMPLATE_MAINPRUDTCTS_TIPS: 'It will be displayed according to your main product categories.',
			TEMPLATE_SEND: 'Post',
			TEMPLATE_BASE: '<span class="bg-ico required"></span>Showcase signage',
			TMPLATE_RECOVER: 'Recover',
			TEMPLATE_DIY: 'Customize template',
			TEMPLATE_DEFAULT: 'Default template',
			TEMPLATE_BASE_TIPS: 'Default appearance',
			TEMPLATE_SET_BASETITLE: 'Showcase signage management',
			TEMPLATE_SET_REQUEST: 'Requirements: ',
			TEMPLATE_SET_REQUESTCONT: '1. Upload an image, width is 1680px, height is 120px in JPG or PNG. Maximum 2M.<br/>2. Make background as succinct as possible, and in compliance with the logo color.',
			TEMPLATE_SET_STYLETIPS: 'Select way of display:',
			TEMPLATE_SET_STYLETIPS1: 'Customize the whole signage',
			TEMPLATE_SET_STYLETIPS2: 'Customize the background',
			TEMPLATE_SET_STYLETIPS3: 'Full measure slider',
			TEMPLATE_SET_STYLETIPS4: 'Showcase slider',
			TEMPLATE_SET_LEGEND: 'Example: ',
			TEMPLATE_SET_SAMPLE: 'Download the example',
			TEMPLATE_SET_UPLOAD: 'Upload a signage',
			TEMPLATE_SET_UPBG: 'Upload image',
			TEMPLATE_SET_SELECTNAME: 'Select color of company name:',
			TEMPLATE_SET_BANNER: 'Hero banner Setting',
			TEMPLATE_SET_BANNER_REQUIRE1: 'Please upload an image, width is 980px, height is 300 px in JPG or PNG. Maximum 1M.',
			TEMPLATE_SET_BANNER_UPLOAD: 'Upload',
			TEMPLATE_SET_ADD_TIPS: 'Add products（<span class="orange"></span>/5）',
			TEMPLATE_SET_ADD_TIPS1: 'Add products（<span class="orange"></span>/9）',
			TEMPLATE_SAVE: 'Save',
			TEMPLATE_SET_IPCNAME: 'Image name',
			TEMPLATE_SET_PRODUCTS: 'Main products Management',
			TEMPLATE_SET_PRODUCTS_TIPS: 'It will be displayed with the latest 3 products.',
			TEMPLATE_SET_PRODUCTS_TIPS2: 'Category',
			TEMPLATE_SET_PRODUCTS_TIPS3: 'Selected(<span class="orange"></span>/7)',
			TEMPLATE_SET_SLLOWBG: 'Slider background:',
			TEMPLATE_SET_SLLOWTIPS: 'Please upload an image of 1680*550px in JPG or PNG. Maximum 2M.',
			TEMPLATE_SET_SLLOWPIC: 'Product slider:',
			TEMPLATE_SET_SLLOWPICIPS: 'Please upload an image of 250*250px in JPG or PNG. Maximum 500KB.',
			ROW: 'row',
			COL: 'column',
			TEMPLATE_SET_HTTPSTIP: 'Enter a site link',
			TEMPLATE_SET_TIPS1: 'Please add at least 1 picture on this module/Add more pictures',
			TEMPLATE_SET_TIPS2: 'Please add at least 3 picture on this module/Add more pictures',
			TEMPLATE_SET_DEFALT: 'Use default',
			TEMPLATE_SET_UPLOADBG: 'Upload a background',
			TEMPLATE_SET_SELECT_BOOTH: 'Select exhibition session:',
			TEMPLATE_SET_ADD_BOOTH: 'Add a booth stand number',
			TEMPLATE_SET_ADD_BOOTHPIC:'Add a booth image',
			TEMPLATE_SET_INNER_BOOTH: 'Please enter all the booth stand numbers in the same hall',
			TEMPLATE_SET_ADD: 'add',
			TEMPLATE_SET_ADD_BOOTHNO: '新增展位号',
			TEMPLATE_SET_UPLOAD_PIC: 'Please upload an image in JPG or PNG. Maximum 2M.',
			TEMPLATE_SET_BOOTH_NAME: 'Image name',
			TEMPLATE_SET_BOOTH_ADD_PIC: 'Add a booth image',
			TEMPLATE_SET_BOOTH: 'Canton Fair on-site booth stand Management',
			DOMAIN_TIPS: 'The site has been taken. Please submit again.',
			DOMAIN_TIPS1: 'Incorrect site. Please submit again.',
			TEMPLATE_SET_SUCCESS: 'sucessfully!',
			TEMPLATE_SET_TIPS3: 'Please choose your main product categories. (No more than 7).'
		},
		MATCH_BUYERS: {
			TITLE: 'Match Buyers',
			CATEGORY: 'Category',
			REGION: 'Country/Region',
			EXHIBITION: 'Participations',
			RECENTLY: 'Lately Participation',
			COMP_TYPE: 'Trading Company',
			PURCHASE_LEVEL: 'Manufacturer',
			VIEW_HISTORY: 'View my Push history',
			SOURCING: 'Sourcing Range:',
			OTHER_FOCUS: 'Other Focus:',
			SEE_MORE: 'See More',
			SEE_LESS: 'See Less',
			FOCUS_MALE: 'He',
			FOCUS_FEMALE: 'She',
			FOCUS_DET: '[@] also likes <a href="javascript:;" role="buyer-sku-hit">[@@]</a>.',
			FOCUS_DETS: '[@] also likes <a href="javascript:;" role="buyer-sku-hit">[@@]</a> and <a href="javascript:;" role="buyer-sku-hit">[@@@] other categories</a>.',
			BUYER_ACT: '<em>Recent Activities: </em>I want to buy "<span>[@]</span>"',
			LOAD_MORE: 'View More Match Buyers'
		},
		PRODUCT_STATISTICS: {
			TITLE: 'Product Traffic Statistics',
			PREVIEW_TIT: 'By timeline',
			AREA_TIT: 'By district',
			NOT_DATA: 'Sorry, no data found.',
			ITEM_WEEK: 'Week',
			ITEM_MONTH: 'Month'
		},
		BUYER_LEAD_MANAGE: {
			TITLE: 'Manage LeadEXpress',
			OPT_BTN: 'Post LeadEXpress',
			TAB_TIT_APPROVED: 'Approved',
			TAB_TIT_AUDITING: 'Pending',
			TAB_TIT_UNAPPROVED: 'Rejected',
			TAB_TIT_EXPIRED: 'Expired',
			TAB_TIT_OFFLINE: 'Private',
			SEARCH_KEYWORD: 'Keywords',
			DELETE: 'Delete',
			ONLINE: 'Public',
			OFFLINE: 'Private',
			PUBLISH_STATE: {
				0: 'New',
				1: 'Updated',
				2: 'Pending',
				3: 'Approved',
				'-1': 'Rejected',
				9: 'Public',
				10: 'Private',
				'-3': 'Deleted'
			},
			TABLE_HEAD_APPROVE: ['', 'Topic', 'Reply Status', 'Latest Reply', 'Posted Date', 'Expire Date', 'Edit'],
			TABLE_HEAD_AUDITING: ['Topic', 'Posted Date', 'Expire Date'],
			TABLE_HEAD_UNAPPROVED: ['', 'Topic', 'Reason', 'Posted Date', 'Expire Date', 'Edit'],
			TABLE_HEAD_EXPIRED: ['Topic', 'Application Status', 'Reply Status', 'Latest Reply', 'Posted Date', 'Expire Date'],
			TABLE_HEAD_OFFLINE: ['', 'Topic', 'Reply Status', 'Latest Reply', 'Posted Date', 'Expire Date', 'Edit'],
			SAVE: 'Save successfully'
		},
		MY_SETTING: {
			TITLE: 'Setting',
			ACCOUNT_SETTING: 'Account Setting',
			PERSON_PROFILE: 'Personal Profile',
			CHANGE_PWD: 'Change Password',
			PREFERENCE_SET: 'Preference Setting',
			COMPANY_PROFILE: 'Company Profile',
			BUSINESS_SETTING: 'Business Setting',
			PUSH_STATE: 'Push Statistics',
			EXPRESS: 'Business Express',
			ACCOUNT_MANAGEMENT:'Account Control',
			VERIFIED: 'verified',
			INFO_INTEGRITY: 'Information Integrity:',
			SAVE: 'save',
			BACK: 'back',
			ACCOUNT: 'Account :',
			COMPANY_NAME: 'Company name :',
			INTRO: 'Introduction :',
			DEPARTMENT: 'Department :',
			CATEGORY: 'Category :',
			CATEGORY_LABEL: 'Please select product category',
			BUSINESS_TYPE: 'Business Type :',
			ESTABLISHED: 'Established :',
			FOUND: 'Found :',
			MAIN_KEYWORD: 'Main keywords :',
			REGION: 'Region/Area :',
			COUNTRY_REGION: 'Country/Region :',
			ADDRESS: 'Address :',
			ADDRESS2: 'Address :',
			ADDRESS_EN: 'Address-EN :',
			ZIP_CODE: 'Zip Code :',
			EMPLOYEE: 'Numbers of Employee :',
			REGISTER_CAPITAL: 'Registered capital :',
			LEGAL_REPRESENTATIVE: 'Legal Representative :',
			BUSINESS_LICENSE: 'Business License :',
			WEBSITE: 'Web Site :',
			UPLOAD: 'Upload',
			UPLOAD_TIPS1: 'Supported format : <em>Jpeg, Jpg, or Png</em> ; less than <em>200K</em> ; Size:<em>160px*160px</em>',
			UPLOAD_TIPS2: 'I guaranteed that I am entitled to have the picture\'s allocation and usage under the terms of use.',
			UPLOAD_TIPS3: 'Supported format : <em>Jpeg, Jpg, or Png</em> ; less than <em>200K</em> ; Size:<em>160px*80px</em>',
			ACCOUNT1: 'Account :',
			NAME: 'Name :',
			FIRST_NAME: 'First name',
			LAST_NAME: 'Last name',
			FULL_NAME: 'Full name',
			GENDER: 'Gender :',
			MALE: 'Male',
			FEMALE: 'Female',
			POST: 'Post :',
			AREA: 'Area :',
			TELEPHONE: 'Telephone :',
			FAX: 'Fax :',
			MOBILE_PHONE: 'Mobile phone :',
			MOBILE_PHONE_CN: 'China Mobile Num :',
			EMAIL: 'Email :',
			ALTERNATE_EMAIL: 'Alternate Email :',
			LANGUAGE: 'Language :',
			WORK_TIME: 'Work Time :',
			MEETING_TIME: 'Meeting Time :',
			SELECT: 'please select',
			PASSWORD: 'Password :',
			CURRENT_PWD: 'Current Password :',
			NEW_PWD: 'New Password :',
			CONFIRM_PWD: 'Confirm Password :',
			UPDATE_PWD: 'Update Password',
			ACTIVATE_EMAIL: 'Activate email login',
			BASE_INFO: 'Base Info',
			TRADING_INFO: 'Trading Info',
			PRIVACY_SETTING: 'Privacy Setting',
			AVATAR: 'Avatar :',
			CONTACT_INFO: 'Contact Info :',
			TARGET_MARKET: 'Target Market :',
			BUSINESS_TIT_1: 'Your Preference of Buyers\'Participation',
			BUSINESS_TIT_2: 'Participation :',
			BUSINESS_TIT_3: 'Lately Participation :',
			BUSINESS_TIT_4: 'What kind of buyers do you prefer?',
			BUSINESS_TIT_5: 'Business Type :',
			BUSINESS_TIT_6: 'Business Nature :',
			BUSINESS_TIT_7: 'Business Type :',
			BUSINESS_TIT_8: 'Business Nature :',
			BUSINESS_TIT_9: 'Annual purchases :',
			PUSH_CONSUMPTION: 'Push Consumption',
			TIMES: 'Times',
			AVERAGE: 'Average',
			PUSH_STATE_1: 'Push performance statistics',
			PUSH_STATE_2: 'Sorry, you have no push record.',
			PUSH_STATE_3: 'Push Info Now!',
			TOTAL: 'Total',
			PRODUCT: 'Product',
			COMPANY: 'Company',
			VIEWS: 'Views',
			COLLECTED: 'Collected',
			COLLECTED_RATE: 'Collected Rate',
			PUSH_RECORD: 'Push record',
			TIME: 'time',
			CONSUMPTION: 'Consumption',
			TO: 'To',
			PERFORMANCE: 'Performance',
			TIPS_TITLE_1: 'Please enter a valid URL.',
			TIPS_TITLE_2: '* This field is required.',
			TIPS_TITLE_3: '* Between 6 and 20 characters (A-Z, a-z, 0-9)',
			TIPS_TITLE_4: 'Password is not matched, please try again.',
			TIPS_TITLE_5: '* Number only',
			TIPS_TITLE_6: '* Minimum 11 numbers required',
			TIPS_TITLE_7: 'Tips: You can login our web, APP, or any terminals by Canton Fair ID, email address.',
			TIPS_TITLE_8: 'Updating your password frequently will enhance your account security.',
			TIPS_TITLE_9: 'If you click “Public”, you are deemed to agree and authorize E-Cantonfair with the free and permanent right to publish and display your photo. The suppliers therefore may view your photo you publishing, which makes them feel close and real, we strongly recommend you to select.',
			TIPS_TITLE_10: 'Set my contact information public(including email, telephone, and etc.)',
			TIPS_TITLE_11: 'Once choosing to set it public, when suppliers contact you, like send you an inquiry, a message, your contact information will be released to them, including email, telephone, and etc.',
			TITLE_TIPS: 'The column marked with<span class="bg-ico required"></span>is required. If you want to change the information that has been verified, please contact customer service by: <em>4006-280-333</em>.',
			SUCCESS_TIPS: 'The information has been saved!',
			SEVRVER_INFO: 'Service Info',
			BUSINESS_EXPRESS: 'Business Express',
			EXP_PACKAGES: 'Packages',
			EACH_BUYER: 'Each Push Buyers:',
			PUSH_TIME1: 'Push Time:',
			EXP_STATE: 'State:',
			EXP_STATETIME: 'Start Time:',
			EXP_EXTIME: 'Expiration Time:',
			EXP_SERTIME: 'Service times:',
			EXP_HASTIME: 'Have service times:',
			EXP_RECORD: 'Business Express Record',
			EXP_TIME: 'Time',
			EXP_PUSHBUYER: 'Push The Buyers',
			EXP_COUNTRY: 'Countries',
			EXP_DETAIL: 'Detail',
			MARK_SELECT: 'Participations and Lately Participation must select!',
			IS_FAV: 'Collect',
			NO_FAV: 'Uncollect',
			SUCCESS: 'success',
			NO_PUSH: 'Sorry, you have no push record.',
			PUSH_NOW: 'Push Info Now!',
			PWD_TIPS: 'Warning: Caps Lock is on.',
			UPDATE_SUCCESS: 'Information save successfully!',
			UPDATE_ERROR: 'Information save failed!',
			DELETE_SUCCESS: 'Information delete successfully!',
			DELETE_ERROR: 'Information delete failed!',
			DELETE_ACCOUNT: 'This account will be used to delete after.',
			ACCOUNT_NAME:'Account name',
			ADD_SUB_ACCOUNT: 'Add Sub Account',
			OPERATE:'Acion',
			UPDATE:'Update',
			DELETE:'Delete',
			BUYER_BUSINESS_TYPE: {
				'i0': 'Buying Office',
				'i1': 'Manufacturers',
				'i2': 'Trading company',
				'i3': 'Wholesaler/Distributor',
				'i4': 'Retailer',
				'i5': 'Broker/Consultant commission-based',
				'i6': 'Government Agency/Organization',
				'i7': 'Other'
			},
			BUSINESS_NATURE: {
				'i0': 'Manufacturers and Wholesalers',
				'i1': 'Small and Medium-sized Wholesalers Group',
				'i2': 'Small Retailers Group ',
				'i3': 'Small Trader Group',
				'i4': 'Other Group'
			},
			ANNUAL_PURCHASE: {
				'i0': 'Below 1 million',
				'i1': '1 to 10 million',
				'i2': '10 to 50 million',
				'i3': '50 to 100 million',
				'i4': 'Over 100 million'
			},
			BUSINESS_SETTING_TIT: {
				'i0': 'Product range you are interested in',
				'i1': 'Business capacity you preferred',
				'i2': 'Typical characters you preferred'
			},
			BUSINESS_SETTING_LABEL: {
				'i0': {
					'title': 'Numbers of Employee :',
					'i0': 'Not limited',
					'i1': 'Below 100',
					'i2': 'Above 5000'
				},
				'i1': {
					'title': 'Registered Capital :',
					'i0': 'Not limited',
					'i1': 'Below 1 million',
					'i2': '1-5 million',
					'i3': '5-20 million',
					'i4': '20-50 million',
					'i5': '50-100 million',
					'i6': '100-1000 million',
					'i7': 'Over 1000 million'
				},
				'i2': {
					'title': 'Annual Turnover :',
					'i0': 'Not limited',
					'i1': 'Below 1 million',
					'i2': '1-10 million',
					'i3': '10-50 million',
					'i4': '50-100 million',
					'i5': 'Over 100 million'
				},
				'i3': {
					'title': 'Business Type :',
					'i0': 'Manufacturer',
					'i1': 'Trading Company',
					'i2': 'Manufacture & Trade Company',
					'i3': 'Others'
				},
				'i4': {
					'title': 'Participations :',
					'i0': 'Not limited',
					'i1': 'At least last 1 session',
					'i2': 'At least 1 session',
					'i3': 'At least last 2 session',
					'i4': '5th+'
				}
			}
		},
		EXPINDEX: {
			MEMBER_LEVEL: {
				'L1': '会员类型',
				'L2': '到期',
				'L3': '会员升级'
			},
			PRO_TOTAIL: '产品数量',
			PUSH_TIME: '推送次数',
			PROCREDIT: '刷卡次数',
			HTO_BUYINGLEAD: '最热采购需求',
			WANT_GETBUYLEAD: '想获取这些采购需求',
			NO_EFFECT: 'no effect'
		},
		STATISTICS: {
			TITLE_CAR: '直通车统计分析',
			CAR: '直通车统计',
			TITLE_EXCHANGER: '交换器统计分析',
			EXCHANGER: '交换器统计',
			DATE_LABEL: '统计日期',
			TO: '至',
			COUNTRY: '国家/地区',
			PUSH_BUYERS: '推送买家数量',
			SWIPE_BUYERS: '刷卡买家数量',
			READ: '阅读数量',
			READ_TOTAL: '阅读总数',
			PUSH_TOTAL: '推荐总量',
			SWIPE_TOTAL: '刷卡总量',
			PRE_PAGE: '上一页',
			NEXT_PAGE: '下一页',
			NAME: '名字',
			TIMES: '参展次数'
		},
		COINS_DETAIL: {
			TITLE: 'C Coins  Detail',
			COST: 'Total cost :',
			BALANCE: 'Balance',
			TYPE: 'Type',
			GIFT: 'Gift',
			CONSUME: 'Consume',
			REWARD: 'Reward',
			RECHARGE: 'Recharge',
			TIME: 'time',
			DETAIL: 'Detail',
			PAYMENT: 'Payment',
			ALL: 'All',
			UNIT: 'coins',
			START_TIME: 'Pt',
			END_TIME: 'Date End',
			TIPS: 'Sorry, no data matches your requirements.'
		}
	},
	BL_DETAIL: {
        NOT_SEARCH_RESULT: 'You don\'t have any matching LeadEXpress.',
        NOT_SEARCH_SUGGEST: 'Please post your products to match.',
		SECRET: 'keep secret',
		TIME_LEFT: 'Time Left :',
		DATE_POST: 'Date Posted :',
		Update: 'Latest Update :',
		CONTACT_NOW: 'Contact Now',
		ADD_CONTACTER: 'Add To Contacter',
		BASE_INFO: "Basic Info",
		MORE_INFO: "More Info",
		HISTORY: 'Contact History',
		CATEGORY: 'Category',
		PUR_AMOUNT: 'Purchase Amount',
		ANNUAL_AMOUNT: 'Annual Purchase Amount',
		DESCRIPTION: 'Description',
		ATTACHMENTS: 'Attachments',
		EXPIRATION_DATE: 'Expiration date',
		PURCHASE: 'Purchase',
		ANNUAL: 'Annual Purchase',
		MODE_OF_TRANSPORT: 'Mode of transport',
		PREFERRED_PRICE: "Preferred Price",
		PORT_OF_ARRIVAL: "Port of arrival",
		SUPPLIER_REQUIREMENTS: "Supplier requirements",
		EXPECT_TO_RECEIVE: "Expect to receive",
		RECOMMEND: 'Recommended',
		UNVERIFY: 'Unverify',
		VERIFY: 'Verify',
		REPLY_HISTORY: 'Reply History',
		MATCH: 'Match:',
		SUBJECT: 'Subject:',
        CONTENT: 'Message: ',
        SEND: 'Send',
        QUESTION: 'How we will treat your response?',
        ANSWER1: 'We will post your reply to the buyer.',
        ANSWER2: 'In order to see your response as soon as possible,we will also send your response to the buyer by e-mail.',
        GUIDE_SING: 'To reply the buying lead, please <a href="/login.html?ut=supplier" rel="nofollow">sign in</a>.',
        GUIDE_SING2: 'To reply the buying lead, please <a id="quote-login" href="javascript:;" rel="nofollow">sign in</a>.',
        GUIDE_JOIN: 'Not a member yet? <a href="/joinfree/?tab=3" rel="nofollow">Join now</a>.',
        CONTACT_DETAIL: 'Contact Detail',
        MESSAGE: 'Message Detail',
		STATUS: 'Status:',
		INQUIRY: 'The Buyer <a href="javascript:void(0);">[@]</a> has to send you the inquiry.',
		SYSTEM_PUSH: 'Your request has been sent through e-Cantonfair.',
		SUPPLIER_REPLY: 'You have submitted the reply request.',
		BUYER_READ: 'Buyers have read your reply.',
		COMPANY: 'Company:',
		CONTACT: 'Contact:',
		EMAIL: 'Email:',
		ADDRESS: 'Address:',
		PUSH_EMAIL: 'System has been send your reply to the buyer by e-mail.',
		BUSINESS_TYPE: 'Business Type:',
		REGION: 'Region:',
		MAIN_PRODUCT: 'Main Product:',
		TEL: 'Telephone: ',
		MOBILE_PHONE: 'Mobile: ',
		OTHER_CONTACT: 'Other Contact',
		FAX: 'Fax:',
		POST: 'Post:',
		PAYMENT: 'Payment Terms',
		EXPIRED_DATE: 'Expiration date: ',
		PURCHASE_AMOUNT: 'Purchase Volume',
		ANNUAL_PURCHASE_AMT: 'Annual Purchase Volume',
		RECOMMEND_TIPS: 'Special recommended by <span>Cantonfair-elite</span>.',
		VERIFY_TIPS: 'Authentication approved by e-Cantonfair.',
		UNVERIFY_TIPS: 'Without authentication approval yet, please tell apart carefully.',
		EXHIBITOR_TITLE: 'October Canton Fair Exhibitor',
		EXHIBITORS_BOOTH_TITLE: '114 exhibitors Booth',
		BOOTH_CLOSE_UP: 'Booth close-up',
		NO_CONTACT_INFO: 'The buyer wouldn\'t like to share the contacts with suppliers.',
		PHASE1: 'Phase 1:',
		PHASE2: 'Phase 2:',
		PHASE3: 'Phase 3:',
		PHASE4: 'Phase 4:',
		MORE: 'more',
		LESS: 'less',
		SPECIAL_PREFERENCES: 'Special Preferences',
		SUPPLIERS_REPLIE: 'All the Suppliers\'s Replie(s)',
		REMINDER: '<span>Reminder:</span>All the time displayed below are Chinese time,GMT+8',
		EXHIBITOR_TIT: 'We exhibit on October Canton Fair',
		BOOTH_NUM: 'Booth Num',
		TARGET_MARKET: 'Target Market',
		CERTIFICATION: 'Mgnt Certification',
		SORRY_TXT: 'Sorry,no replies currently.',
		ADVICE_TXT: 'Maybe you could try the following...',
		POST_BL: 'posted buying lead',
		AD_TXT1: '10 seconds to post what you want!',
		AD_TXT2: 'Thousands of buyers are trying to use it,and you?',
		ADD_COMMENT: 'Add a comment',
		EXHIBIT_IN_OCTOBER: 'Exhibit in October',
		BUYER_INFO: 'Buyer’s Contact Info',
		TIPS: 'This buyer would like to get your message and contact info through e-cantonfair.com.',
		CONTACT_BUYER: 'Contact the Buyer',
		CONTACT_TIPS: '(To improve the arrival rate of your email, reply through e-Cantonfair.com is pratically more effective.)',
		INTER_MSG: 'Enter your message',
		YOUR_CONTENT: 'Your Reply Content:',
		MSG_DETAIL: 'Enter your message details such as:<br/> -The product details<br/> -Quotation<br/> -Production Capacity',
		START_TIPS: 'Put it into your collection, <BR/>read it anytime <BR/>from "Type" selector.',
		SEND_SUCCESS: 'Send successfully!',
		PHONE: 'Telephone:',
		FROM: 'From',
		TO: 'To',
		L_DETAIL: 'LeadEXpress Detail',
		NEED_COINS: 'It  need 10 C coins to view the contact,',
		REWARD: '<span>Tips:</span>If you reply this LeadEXpress ,you will Reward ',
		TIPS_COINS2: 'C coins',
		CONSUME: '<span>Tips:</span>The LeadEXpress has get enough response.Reply it ,need ',
		CONIS: 'Coins',
		LIMIT: 'Contact the application has reached the upper limit.<br/>The operation needn\'t any C coins.',
		C_COINS: 'You have the opportunity to award when you reply this LeadEXpress',
        VIEW: 'View: ',
        RELY: 'Rely: ',
        UNMATCH_TIPS: '<span></span>Note: You are NOT likely to see buyer contacts, since this LeadEXpress is not matched your industries. However, your quotation is sent successfully, buyer is able to reply your quotation.',
        UNLOGIN_TIPS: '<span></span>View buyer\'s contact info,please <a href="javascript:;" rel="nofollow">Sign in</a> now!',
        UNQUOTE_TIPS: '<span></span>Note: Buyer contact details are invisible. Reply quotation to display it now!',
        BUYER_TIPS: '<span></span>You\'re a buyer，can\'t view the buyer contact info!',
        QUOTE_NOW: 'Quote Now',
        SELECT_PRO_TIPS: 'Select one product from my product list',
        RESELECT: 'Reselect',
        YOUR_QUOTE: 'Your Quote: ',
        MOQ: 'MOQ: ',
        QUOTE_TILL: 'Quotation Valid Till: ',
        SELECT_PRO: 'Select Product: ',
        QUOTE_DETAIL: 'Your Quote Detail',
        YOUR_MESSAGE: 'Your message: ',
        QUOTE_FOR: 'My quote:',
        FORBID_TIPS1: 'You\'re a buyer,you can\'t quote the LeadEXpress.',
        FORBID_TIPS2: 'Sorry, you have sent 100 quotation replies today (Limited to 100 pieces/day). Please try tomorrow.',
        TIP_TITLE_12: 'Tips',
        TIP_MSG: 'Although E-cantonfair.com aims to provide you with accurate Sender Details, we are not able to fully guarantee the accuracy of every Sender\'s IP information. E-cantonfair.com is neither responsible nor liable for any of the above information。'
    },
	BUYER_ACTIVITY: {
		TIT: {
			BROWSE_PRO: 'browsed your product', //浏览产品
			BROWSE_INFO: 'browsed your company info',
			EXCHANGE_CARD: 'exchanged card with you', //交互名片
			COLLECTED_PRO: 'collected your product', //收藏产品
			COLLECTED_INFO: 'collected your company info',
			SEND_INQ: 'sent a inquire to you', //发询盘
			INTEREST: 'is very interested in your company',
			BROWSE_BE: 'browsed your Business Express', //企业速递
			BROWSE_PUSH: 'browsed your push',
			//all
			BROWSE_PRO_ALL: 'browsed the product',
			BROWSE_INFO_ALL: 'browsed a company info',
			EXCHANGE_CARD_ALL: 'exchanged card with the supplier',
			COLLECTED_PRO_ALL: 'collected a product',
			COLLECTED_INFO_ALL: 'collected a company info',
			SEND_INQ_ALL: 'sent an inquiry',
			SEARCH: 'wanted to find a product', //搜索产品
			POST_BL: 'want to source the product', //发采购需求
			ALL_ACTIVITIES: 'All Activities',
			MY_STATUS: 'My Status'
		},
		DESC: {
			BROWSE_PRO: '%(user)s from %(region)s browsed your product of the category "%(data)s"',
			INDEX_BROWSE_PRO: '%(user)s from %(region)s browsed your product "%(data)s"',
			BROWSE_INFO: '%(user)s from %(region)s browsed your company info.',
			EXCHANGE_CARD: '%(user)s from %(region)s, %(data)s Collect your business cards. And add you as a contact',
			COLLECTED_PRO: '%(user)s from %(region)s is interesting in the product of the category "%(data)s"',
			INDEX_COLLECTED_PRO: '%(user)s from %(region)s is interesting in your product "%(data)s"',
			COLLECTED_INFO: '%(user)s from %(region)s collected your company info.',
			SEND_INQ: '%(user)s from %(region)s is interesting in the product "%(data)s"',
			INTEREST: '%(user)s from %(region)s is interested in your company.',
			BROWSE_BE: '%(user)s from %(region)s, browsed your business express.',
			BROWSE_PUSH: 'browsed your push.',
			RBH: 'Recently Browsed History',
			//all
			BUSINESS: 'want to purchase [%s]',
			BROWSE_PRO_ALL: '%(user)s from %(region)s browsed a product of the category "%(data)s"',
			BROWSE_INFO_ALL: '%(user)s from %(region)s browsed a %(data)s company information.',
			EXCHANGE_CARD_ALL: 'exchanged card with the [%s] supplier.',
			COLLECTED_PRO_ALL: '%(user)s from %(region)s collected the product of "%(data)s" ',
			COLLECTED_INFO_ALL: '%(user)s from %(region)s collected a %(data)s company information.',
			SEND_INQ_ALL: '%(user)s from %(region)s sent an inquiry to the %(data)s supplier.',
			SEARCH: '%(user)s from %(region)s, was searching "%(data)s"',
			POST_BL: '%(user)s from %(region)s want to source the product "%(data)s"'
		},
		MORE_TIP: 'Viw More Activities',
		LIVE_TIP: 'The 114th Cantonfair buyer',
		PRIVATE_TIP: '<span class="red">Notice:</span> Product imagesas below are invisible due to the private setting.'
	},
	SELLER_INDEX: {
		SEARCH_BL: 'Search LeadEXpress',
		ADD_PRO: 'Add Product',
		INFO_INTEGRITY: 'Profile Completeness:',
		IMPROVE: 'Update Now!',
		INTEREST: 'Buyers you may be interested in',
		ALL_STATUS: 'All Activities',
		MY_STATUS: 'Relevance',
		ALSO_U_CAN: 'Or you can also',
		KEYWORD: 'Keywords',
		NOTICE: '更新公告',
		NOTICE_CONTENT: '2月25日更新内容如下：',
		REWARD_TIP1: '平台网站展台&产品开放访问',
		TIP1_CONT1: '1.游客可搜索查看产品及供应商列表，并且无需登录即可查看展台页面及产品详情。<br/>2.游客可直接询盘（询盘后登录）',
		REWARD_TIP2: '产品管理',
		TIP2_CONT1: '1、新增产品审核业务，供应商发布的产品须经过平台审核通过才能上线供买家查询。<br/>2、新增产品上下线功能，通过审核的产品，供应商可以任意设置上下线。<br/>3、新增橱窗产品设置，设置为橱窗产品将在买家搜索的结果页面当中，获得优先推荐（橱窗产品搜索结果优先显示将会在3月15日推出，供应商可先把产品预先设置，做好准备）。'
	},
	BUYER: {
		INDEX: {
			VIEW_OPP: 'Manage Collections',
			POST_BL: 'Post LeadEXpress',
			INFO_INTEGRITY: 'Profile Completeness:',
			IMPROVE: 'Update Now!',
			SEARCH_PLD: 'input a keyword',
			OPP_TIT: 'Opportunities you may like',
			MSG_GUIDE: 'Your [@] network: [@@] [@@@]',
			ALL_RECOMMEND: 'All',
			TYPE_1: 'presents you with their company and products.',
			TYPE_2: ' introduces their company to you.',
			TYPE_3: ' introduces products to you.',
			TYPE_4: 'send a greeting to you.'
		},
		PURCHASE_PREFER: {
			TOP_TIT: '<span class="ico"></span><p class="des">Tips: Customize your purchasing preferences to easily enjoy matching services.</p>',
			STEP_1_TIT: '<span class="ico"></span><h3>Select product categories<em class="tips">(maximum 3 categories)</em></h3>',
			STEP_2_TIT: '<span class="ico"></span><h3>Business capacity you preferred</h3>',
			STEP_3_TIT: '<span class="ico"></span><h3>Typical characters you preferred</h3>',
			STEP_4_TIT: '<span class="ico"></span><h3>Do you have any speical requirements on suppliers\' participation experiences?</h3>',
			STEP_2_1_TIT: '<span class="mrk"></span><h3>Numbers of Employee</h3>',
			STEP_2_2_TIT: '<span class="mrk"></span><h3>Registered Capital</h3>',
			STEP_2_3_TIT: '<span class="mrk"></span><h3>Annual Turnover</h3>'
		},
		SEARCH: {
			TYPE: "Categories:",
			TAG: "Tag:",
			SOURCE: "Source:"
		}
	},
	CATE_SELECTOR: {
		TITLE: 'Select Category',
		SELECTED: 'Selected:',
		RETURN_TREE: 'Back',
		SAVE: 'Save'
	},
	PUSH_WINDOW: {
		PUSH_TIT: 'Push Information',
		TEXT_PLACE: 'Tips:																									1. Always on the topic. Make your content relevant to buyers\' behavior and target products .						 2. Use English. Highlight main products, core competence, target market, brand experience and etc.',
		YOU_SAY: 'Please make an introduction about your product and company.',
		YOU_SHARE: 'You can share one of your product with <strong>[@]</strong>.',
		SHARE_COINS: 'It requires <em>[@] C Coins</em> for this push. Due to promotion period, it\'s free of charge now.',
		PUSH_SUCCESS: 'Push info sent successfully!',
		REPEAT_PUSH: 'Please do not repeat push'
	},
	MESSAGE_WINDOW: {
		WRITE_TIT: 'Send an Email',
		READ_TIT: 'Mail details',
		REPLY_TIT: 'Reply email',
		INQUIRY_TIT: 'Send a Inquire',
		SUBJECT: 'Subject: ',
		TO: 'To: ',
		CONTENT: 'Message: ',
		SUBJECT_PH: 'Add a subject',
		FROM: 'From: ',
		TIME: 'Time: ',
		REPLY: 'Re: ',
		DEL_TIPS: 'Move message to trash successfully!',
		QUICK_RE_TIPS: 'Reply email successfully!',
		INQUIRY_SUBJECT: 'I\'m interested in your [@]',
		QUICK_RE_PD: 'Write a message, and press &quot; Enter &quot; to send'
	},
	INFO_WINDOW: {
		SUPPLIER_TIT: 'The Manufacture information',
		BUYER_TIT: 'Buyer Profile',
		BASE_INFO: 'Basic Info',
		FOLLOW: 'Follow',
		EVALUATE: 'Credit Evaluation',
		ACTIVITY: 'Recent/Updates',
		PREFERENCE: 'My Preferences',
		BUYER_PROFILE: 'Buyer Profile',
		SUPPLIER_PROFILE: 'Manufacture Profile',
		COMPANY_PROFILE: 'Company Profile',
		GENDER: 'Gender: ',
		POSTS: 'Posts: ',
		EMAIL: 'Email: ',
		PHONE: 'Telephone: ',
		FAX: 'Fax: ',
		ADDRESS: 'Address: ',
		ZIP: 'Zip Code: ',
		SKYPE: 'Skype: ',
		TELEPHONE: 'Telephone',
		COMPANY: 'Company: ',
		TYPE_BUYER: 'Type of Buyer: ',
		NATURE_BUYER: 'Nature of Buyer: ',
		ESTABLISHMENT_TIME: 'Establishment Time: ',
		EMPLOYEES: 'Employees: ',
		ANNUAL: 'Annual Purchasing: ',
		TYPE_SUPPLIER: 'Company Type: ',
		MAIN_PRODUCT: 'Main products: ',
		STAFF: 'Staff: ',
		REGISTERED: 'Registered: ',
		PRIVACY: '<span class="ico"></span><p class="des">Buyer has set part of [@] contact info private.<br /><a href="javascript:;" action="push">Push info</a> to the buyer and introduce yourself to make first contact, which only takes you [@@] C coins.</p>',
		PRIVACY_APPLY: '<span class="ico"></span><p class="des">Buyer has set part of [@] contact info private.<br /><a href="javascript:;" action="say">Say hi to [@@]</a> and ask for [@] permission to release the contact.</p>',
		APPLY_TIPS: 'You are now requesting [@] for [@@] private info, you can chat here.',
		APPLY_MALE: 'his',
		APPLY_FEMALE: 'her',
		REMARKS: 'Remarks: ',
		GROUP: 'Group: ',
		ADD_TO: 'Add to',
		ADD_CONTACT_TIPS: 'The buyer had been added to your contacter!',
		SAVED: 'Save successfully!',
		BUYER_INFO_TIT: 'The buyer information',
		MATCH: 'Relevance: ',
		MATCH_PRO: 'Product',
		PRO_TITLE: 'Product Relevance: ',
		MATCH_BG: 'Background',
		BG_TITLE: 'Background Relevance: ',
		MARKET: 'Market: ',
		PART: 'Participation activity: ',
		NATURE: 'Business nature: ',
		LATELY: 'Lately Participation: ',
		TYPE: 'Company Type: ',
		SKU_TITLE: '\'s activity on Canton Fair',
		ACTIVITY_TITLE: 'All Activities',
		ACTIVITY_EMPTY: 'No activities about the buyer',
		BOOTH_CLEANUP: 'Visit Booth',
		TAB: {
			PRODUCT: 'Product',
			CONTACT: 'Contact',
			INTRO: 'Introduction',
			BOOTH: 'Visit Booth'
		},
		FEMALE: 'Female',
		MALE: 'Male',
		BRAND_EXP: 'Brand Experience: ',
		BOOTH_TIT: 'We exhibit on October Canton Fair',
		BOOTH_TIPS: '[@]th Booth Stand Num: ',
		PHASE: 'Phase [@]: ',
		NOT_PRODUCT: 'It seems that the supplier has not prepared their product display yet.',
		NOT_INTRO: 'It seems that the supplier has not prepared their introduction yet.',
		NOT_BOOTH: 'It seems that the supplier has not prepared their booth information yet.',
		SUGGEST_ACTION: 'Click the button <a href="javascript:;" role="contact">View Contact</a> to make contact directly!',
        VERIFY_TIPS_NOTE: 'Note: ',
        VERIFY_TIPS_UNV: 'The buyer is unverified yet.',
        VERIFY_TIPS_DIS: 'The buyer is disapproved.'
	},
	POST_BUYING_LEAD: {
		ATTENDING: "Attending Canton Fair: ",
		NOT_THIS_YEAR: "No, not this year.",
		I_AM_HERE_NOW: "Yes, I am here now.",
		IN_THIS_APRIL_OCTORBER: "Yes, in this April or Octorber.",
		RECEIVE_FEEDBACKS: "Receive Feedbacks",
		CHECK_EMAIL: "Check the feedbacks by email or e-cantonfair.com",
		GET_RECOMMENDATIONS: "Get Recommendations",
		GET_REC_BY_EMAIL: "Get recommendations by email",
		TELL_US_WHAT_YOU_NEED: "Tell us what you need",
		LEARN_MORE: "Learn More &gt;&gt;",
		TITLE: "Post LeadEXpress",
		PRODUCT_NAME: "Product Name:",
		DETAIL: "Description:",
		THIS_QUANTITY: "Purchase Quantity:",
		YEAR_QUANTITY: "Annual Purchase:",
		DATE_LIMIT: 'Valid to:',
		TRANSPORT: "Transported by:",
		FIRST_PRICE: "Preferred Price:",
		DESTINATION: "Loading Port:",
		PAYMENT: 'Payment Terms:',
		SUPPLIER_TYPE: 'Special Requirements:',
		CONDITION_1: "Canton Fair Exhibitor",
		CONDITION_2: "Brand Experience",
		HOPE_RECEIVE: 'Extra Required:',
		DETAIL_MENU: "Specifications/Catalog",
		DETAIL_PRICE: "Quotation",
		CERT: 'Certification',
		OTHER: 'Others',
		MORE_INFO: 'More additional information',
		TIPS: 'Complete trade information can help buyers to make better purchasing decisions.',
		NON_REQUIRED: 'non-required',
		UNIT: 'Unit type',
		ATTACH_TIPS: 'Maximum of <em>3</em> attachments(<em>2MB</em>/each, <em>doc,docx xls,xlsx, ppt,pptx, txt, pdf</em> supported)',
		UPLOAD_TIPS:'Format:<em>jpg/jpeg, gif, png,doc/docx,xls/xlsx,ppt,pdf</em>; Each Maximum Size:2MB',
		LETTER_TIPS: 'Message should contain 20-8000 characters',
		PRODUCT_DESCRIPTION_TIPS:'Please enter your detail inquiry like: <br> &nbsp;&nbsp;- Exact Product Name<br>&nbsp;&nbsp;- Size/Dimension<br>&nbsp;&nbsp;- Grade/Quality Standard <br>&nbsp;&nbsp;- Material <br> &nbsp;&nbsp;- Application <br> &nbsp;&nbsp;- Packaging/Packing <br> &nbsp;&nbsp;- Any other special factors you care about',
		PER: 'per'
	},
	FAVORITE: {
		ALREADY_ADDED: 'The tag have been added'
	},
	CALENDAR: {
		CURRENT: '[@]/[@@]',
		BUTTON_TEXT: ['↑', '←', '→', '↓'],
		WEEK: 'Sun Mon Tues Wed Thur Fri Sat'
	},
	TPL_SHOWROOM: {
		COMP_NAME: 'Company name',
		ESTABLISHED: 'Established',
		VERIFIED: 'verified',
		MPC: 'Main Products',
		COMP_TYPE: 'Business Type',
		REGION: 'Country/Region',
		ADDRESS: 'Address',
		ZIP_CODE: 'Zip Code',
		NOE: 'No. of Employees',
		REG_CAP: 'Registered Capital',
		BUS_LICE: 'Business License',
		WEBSITE: 'Website',
		COMP_INTRO: 'Company Intro',
		SLOGAN: 'Slogan',
		BRIEF_INTRO: 'Brief Introduction',
		CHAR_LEFT: 'characters left',
		CONTACT_INFO: 'Contact Info',
		TEL: 'Telephone',
		FAX: 'Fax',
		MOBILE: 'Mobile',
		SKYPE: 'Skype',
		FACEBOOK: 'Facebook',
		VI_PRE: 'Company Presentation',
		COMP_LOGO: 'Company Logo',
		UPLOAD_LOGO_FORMAT: 'Format:<em>Jpg, Gif, Png</em>; Each Maximum Size:<em>1MB</em>; Suggest Picture Size:<em>120*70 pixels</em>',
		COMP_TOUR: 'Videos',
		UPLOAD_VIDEO_FORMAT: 'Format Maximum <em>30MB</em> FLV video; the Video Length is no more than <em>60</em> seconds',
		COMP_VISION: 'Company Vision',
		UPLOAD_IMAGE_FORMAT: 'Format:<em>Jpg, Gif, Png</em>; Each Maximum Size:<em>1MB</em>; Maximum Picture No.:8',
		FACTORY_SIZE: 'Factory Size',
		ODM_EXPERIENCE: 'Experience in ODM',
		OEM_EXPERIENCE: 'Experience in OEM',
		EXPERIENCE_OUTLINE: 'Experience Outline',
		ENGINEER_TOTAL: 'No. of Engineer',
		RDS_TOTAL: 'No. of R&D Staff',
		QCS_TOTAL: 'No. of QC Staff',
		CERT: 'Certification',
		REQUIRE: 'This field is required.',
		PBOYE: 'Please briefly outline  your experiences.',
		MAIN_TARGET_MARKET: 'Main Target Market',
		DELIVERY_TERMS: 'Delivery Terms Acceptable',
		PAYMENT_ACCEPTABLE: 'Payment Currency Acceptable',
		PAYMENT: 'Payment Terms',
		LOADING_PORT: 'Loading Port',
		LEAD_TIME: 'Delivery Deadline',
		SAMPLE_AVAILABLE: 'Sample Available',
		DAY: 'Day(s)',
		SAVE: 'Save',
		YES: 'Yes',
		NO: 'No',
		SQUARE_METER: 'Square Metars',
		INDUSTRY: 'Industry',
        MANUFACTURER: 'Manufacturer',
        TRADING:'Trading Company ',
        MANUFACTURE_TRADING:'Manufacture & Trading Company',
        DOMESTIC:'Domestic Company',
        OTHERS:'Others',
        SELECTED: "Please select",
        BELOW_100:'Below 100',
        PEOPLE_499:'100-499',
        PEOPLE_999:'500-999',
        PEOPLE_999:'1000-4999',
        OVER_5000:'Over 5000'
	},
	cclick: {
		l1: 'your posted LeadEXpress',
		l2: 'LeadEXpress',
		l3: 'Product images',
		l4: 'Purchase Quantity',
		l5: 'Application & Usage',
		l6: 'Material',
		l7: 'Other Specifications(e.g. Dimension)',
		l8: 'Background Info',
		l9: 'Request more from @',
		l10: 'What else do you want to know about this @?<br>Select at most 4 applicable.',
		l11: 'C-Click, your handy tool to request buyer to provide more details.',
		l12: 'got it',
		l13: 'Please select at least one more item',
		l14: 'Don\'t check more than @ items',
		l15: "Send successfully!",
		l16: 'buyer',
		l17: 'supplier',
		l18: 'LeadEXpress',
		l19: 'Relevant Product Image',
		l20: 'Technical Data & Specifications',
		l21: 'Price List',
		l22: 'Certifications',
		l23: 'Export Experience on Relative Products',
		l24: 'Background Info & Brand Experience',
		l25: 'Click for more details'
	}
};
